Repository bonitasoft/bonita-doc, pull requests merged in 2018-04, with the labels that each got.

#499 fix(engine http client): add a warning about client/server versions
  md/configure-client-of-bonita-bpm-engine.md
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/performance-tuning.md
Labels: Review needed

#502 doc(SEO): Add lines to explain what we need to do to improve our SEO
  CONTRIBUTING.md
Labels: Review needed

#503 fix(ReleaseNote): add a note about the behavior change in API method
  md/release-notes.md
Labels: Review needed

#507 thanks for contribution in realease note
  md/release-notes.md
Labels: Review needed

#506 fix(naming): remove references to Bonita BPM
  md/bpm-api.md
  md/deploy-bundle.md
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/rest-api-overview.md
  md/sap-jco-3.md
  md/set-up-continuous-integration.md
  md/single-sign-on-with-cas.md
Labels: Feedback integrated, Review done

#518 delete IAM role description
  md/install-a-bonita-bpm-cluster.md
Labels: Review needed

#496 fix(doc): Update filters for /API/bpm/humanTask
  md/bpm-api.md
Labels: Review done
