Repository bonitasoft/bonita-doc, pull requests merged in 2018-05, with the labels that each got.

#529 doc(BDM): document usage & limitations of alternative SchemaManager
  md/define-and-deploy-the-bdm.md
Labels: Review done

#530 feat(uid) explicit the split of the uid and engine web container
  md/release-notes.md
  md/ui-designer-overview.md
Labels: Review done

#534 rn(designer) update of the designer webapp name
  md/release-notes.md
Labels: Feedback integrated

#522 doc(release-note): Update Release Notes
  md/release-notes.md
  md/ui-designer-overview.md
Labels: Feedback integrated, Rebase needed, Review done

#533 improvement(ldap sync): improve groups synchronization section
  md/ldap-synchronizer.md
Labels: Ready to merge, Review done

#456 Add Cybersecurity Best Practices
  md/first-steps-after-setup.md
Labels: Feedback integrated, Rebase needed, Review done

#511 doc (profileCreation): restructure, fix
  md/profileCreation.md
Labels: Feedback integrated, Review needed
