Repository bonitasoft/bonita-doc, pull requests merged in 2018-10, with the labels that each got.

#594 fix(log): Fix typo User profile with U upper case
  md/manage-users.md
Labels: Review done

#597 fix(Studio Preferences): document new Tomcat JVM args settings
  md/bonita-bpm-studio-preferences.md
Labels: Review needed

#600 doc(licensing): document existence of Enterprise license
  md/licenses.md
Labels: Review needed

#601 doc(licensing): document usage of Enterprise license
  md/deploy-bundle.md
  md/multi-tenancy-and-tenant-configuration.md
  md/tomcat-bundle.md
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Review needed

#593 fix(log): remove reference to sfl4j version
  md/logging.md
  md/technical-logging.md
Labels: Question Answered, Review done

#602 rn(spring): upgrade to lastest available versions
  md/release-notes.md
Labels: Ready to merge

#582 del(6x legacy forms): delete
  md/6-x-legacy-forms.md
  md/actors.md
  md/bonita-bpm-overview.md
  md/bonita-bpm-portal-urls.md
  md/comparison-of-7-x-and-6-x.md
  md/diagram-tasks.md
  md/import-and-export-a-process.md
  md/licenses.md
  md/migrate-a-form-from-6-x.md
  md/migrate-a-process-from-bonita-open-solution-5-x.md
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/migration-overview.md
  md/optimize-user-tasklist.md
  md/overview-of-bonita-bpm-in-a-cluster.md
  md/page-and-form-development-overview.md
  md/preloading-the-forms-cache.md
  md/software-extensibility.md
  md/subtasks.md
  md/tasks.md
  md/taxonomy.md
Labels: Change Needed, Question Asked

#603 fix(Kerberos) Kerberos documentation feedback
  md/single-sign-on-with-kerberos.md
Labels: Review needed

#595 refactor(code sample): rewrite code samples to use APIClient
  md/manage-users.md
Labels: Ready to merge, Review done

#606 refactor(code sample): rewrite code samples to use APIClient
  md/handle-a-failed-activity.md
Labels: Review needed

#605 feat(uid) Adding modal documentation
  md/uid-modal-tutorial.md
  md/widgets.md
Labels: Feedback integrated

#598 Fix jaas file path Windows vs Linux
  md/active-directory-or-ldap-authentication.md
Labels: Review done

#612 Update the app descriptor documentation according to the changes on Bonita 7.8
  md/applicationCreation.md
Labels: Review needed

#609 Add missing details on the profile documentation
  md/profileCreation.md
Labels: Question Answered, Ready to merge, Review done
