Repository bonitasoft/bonita-doc, pull requests merged in 2018-11, with the labels that each got.

#616 feat(release-note 7.8): start
  md/release-notes.md
Labels: Feedback integrated, Review needed

#620 feat(taxonomy/mig change log): add page
  md/migration-tool
  md/taxonomy.md
Labels: Review needed

#608 feat(event): remove ARCHIVED_FLOWNODE_INSTANCE event
  md/event-handlers.md
Labels: Ready to merge

#618 feat(index): create
  md/index.md
Labels: Review needed

#625 feat(7.7.5): add RN for 7.7.5 release
  md/release-notes.md
Labels: Feedback integrated, Review needed

#628 feat(migration): add release notes for 2.35.0
  md/migration-tool.md
Labels: Review needed

#617 imp(bpm api): add anchor for message
  md/bpm-api.md
Labels: Review needed

#633 doc(RN 7.8): typo fix + add missing CR's
  md/release-notes.md
Labels: Ready to merge

#627 fix (workspaces-and-repositories.md):note on shared repositories
  md/workspaces-and-repositories.md
Labels: CLA not signed, Review done

#615 fix(modal container) modal container limitations
  md/widgets.md
Labels: Feedback integrated, Review needed

#622 fix(widgets): remove widget after container
  md/widgets.md
Labels: Review done

#621 fix(how to modal): change link to modal page
  md/uid-modal-tutorial.md
Labels: Review done

#569 fix(workspace api): state it is deprecated as of Bonita 7.7
  md/automating-builds.md
  md/set-up-continuous-integration.md
  md/software-extensibility.md
Labels: Feedback integrated, Review needed
