Repository bonitasoft/bonita-doc, pull requests merged in 2018-03, with the labels that each got.

#485 fix(date) Add precision about time zone management into rest api (#484)
  md/rest-api-extensions.md
Labels: Ready to merge

#488 fix layout
  md/bdm-access-control.md
Labels: Feedback integrated

#487 feat(workspaceAPI) deprecate workspace API
  md/automating-builds.md
  md/release-notes.md
  md/set-up-continuous-integration.md
Labels: Review done, Review needed

#495 doc(UID): Readable id of artifact and renaming
  md/ui-designer-overview.md
Labels: Review needed

#500 fix(ReleaseNote): add a note about the new API method
  md/release-notes.md
Labels: Feedback integrated, Review needed
