Repository bonitasoft/bonita-doc, pull requests merged in 2018-06, with the labels that each got.

#535 feat(git) initiate troubleshooting section
  md/workspaces-and-repositories.md
Labels: Feedback integrated

#544 feat(case overview) update tutorial
  md/uid-case-overview-tutorial.md
Labels: Ready to merge, Review done

#546 tr(technos): document technology updates for Spring
  md/release-notes.md
Labels: Review needed

#536 promote BCD 2
  md/release-notes.md
Labels: Ready to merge

#541 doc(share with git): numbers, tips, typos
  md/share-a-repository-on-github.md
Labels: Review needed

#542 doc(release notes): reorder, add items
  md/release-notes.md
Labels: Feedback integrated, Review needed

#540 doc(workspaces): git clone 7.6 and git status
  md/workspaces-and-repositories.md
Labels: Ready to merge

#548 fix(archive): wrong bold settings
  md/configurable-archive.md
Labels: Review needed

#545 fix(SAML) tomcat conf in troubleshooting section
  md/logging.md
  md/single-sign-on-with-saml.md
Labels: Review needed

#510 fix(escape character) Remove escape character if used into quote ``
  md/application-api.md
  md/bpm-api.md
  md/customuserinfo-api.md
  md/identity-api.md
  md/portal-api.md
Labels: Feedback integrated, Review needed

#554 feat(ribbon) Change 7.3 ribbon, for "Out of support"
  md/images/outOfSupport.png
  scripts/convertMdToHtml.js
Labels: Question
