Repository bonitasoft/bonita-doc, pull requests merged in 2018-07, with the labels that each got.

#556 Update release-notes.md
  md/release-notes.md
Labels: Ready to merge

#559 doc(mysql): clarify which versions we officially support
  md/hardware-and-software-requirements.md
Labels: Review needed

#552 feat(studio install): add Linux blank welcome page troubleshooting
  md/bonita-bpm-studio-installation.md
  md/images/studio_welcome_page_ko.png
  md/images/studio_welcome_page_ok.png
Labels: Ready to merge

#557 feat(6xForms) add release note item about 6x forms removal
  md/release-notes.md
Labels: Change Needed, Review done

#563 fix(migration) update permission files migration procedure
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review needed

#516 Update bpm-api.md
  md/bpm-api.md
Labels: Rebase needed, Review done

#498 changes after a cluster installation with a customer
  md/install-a-bonita-bpm-cluster.md
Labels: Review done

#539 doc(BDM AC): add the make several app options
  md/bdm-access-control.md
Labels: Feedback integrated, Review needed
