Repository bonitasoft/bonita-doc, pull requests merged in 2018-12, with the labels that each got.

#624 feat(rel-notes): add performance improvements
  md/release-notes.md
Labels: Ready to merge, Review done

#634 doc(uiTranslate): Explain how to translate a string in javascript exp…
  md/multi-language-pages.md
  md/release-notes.md
Labels: Change Needed, Review done

#623 fix(SAML SSO): correct and improve configuration instructions
  md/single-sign-on-with-saml.md
Labels: Review done

#619 doc(rest api): Update REST API extension documentation to cover Community Edition
  md/rest-api-extensions.md
Labels: Feedback integrated, Review needed

#638 rn(migration-tools): add 2.36.0 release notes
  md/migration-tool.md
Labels: Review needed

#631 change(hw-sw-req): remove mobile
  md/hardware-and-software-requirements.md
Labels: Ready to merge

#639 rn(7.8.0): add bug fixes
  md/release-notes.md
Labels: Review needed

#596 feat(git) migrate a svn repository to git
  md/migrate-a-svn-repository-to-github.md
  md/taxonomy.md
Labels: Feedback integrated, Review done

#641 rn(migration): add release notes for 2.36.1
  md/migration-tool.md
Labels: Review needed

#629 change(hw and sw requirements): change JDK8
  md/hardware-and-software-requirements.md
Labels: Question Asked, Review done

#644 fix(real_note): add jump to line in uiPath
  md/release-notes.md
Labels: Review needed

#636 doc(Custom profiles)add note about long menus
  md/custom-profiles.md
Labels: Rebase needed

#643 fix(push config) add warning to avoid override config
  md/BonitaBPM_platform_setup.md
  md/api-extensions.md
  md/resource-management.md
  md/rest-api-authorization.md
Labels: Change Needed, Question Asked, Review done
