Repository bonitasoft/bonita-doc, pull requests merged in 2018-09, with the labels that each got.

#567 typo(widgets): fix typo
  md/widgets.md
Labels: Rebase needed

#581 fix(Languages): add warning for translation of Mobile Portal
  md/languages.md
Labels: Review needed

#583 feat(message) add rest api bpm/message
  md/bpm-api.md
Labels: Review needed

#587 Update ldap-synchronizer.md
  md/ldap-synchronizer.md
Labels: Review done

#592 doc(cluster):Make cluster installation consistent
  md/install-a-bonita-bpm-cluster.md
Labels: Rebase needed
