Repository bonitasoft/bonita-doc, pull requests merged in 2019-02, with the labels that each got.

#661 feat(java11) rest api extension migration
  md/release-notes.md
Labels: Ready to merge, Review done

#657 rn(java11): groovy lib upgrade
  md/release-notes.md
Labels: Review needed

#656 fix(migtool-chglog): update rel. date for 2.37.0
  md/migration-tool.md
Labels: Change Needed

#659 feat(howto): add a howto to display vertical tabs on all devices
  md/images/vertical-tabs-container-tutorial/configuration.png
  md/images/vertical-tabs-container-tutorial/css.png
  md/images/vertical-tabs-container-tutorial/desktop.png
  md/images/vertical-tabs-container-tutorial/mobile.png
  md/taxonomy.md
  md/uid-vertical-tabs-container-tutorial.md
Labels: Review needed

#671 Update Groovy script doc to reflect 7.8 changes
  md/expressions-and-scripts.md
Labels: Review needed

#676 fix(rel_notes): migration info for V6 forms
  md/release-notes.md
Labels: Review needed
