Repository bonitasoft/bonita-doc, pull requests merged in 2019-06, with the labels that each got.

#753 Document Git usage on Community Editon
  md/git-versioning-community-edition.md
  md/taxonomy.md
  md/workspaces-and-repositories.md
Labels: Review needed

#761 chore(links): fix all dead links in 7.8 doc
  md/bonita-bpm-studio-preferences.md
Labels: Review needed

#762 chore(links): fix all dead links in 7.9 doc
  md/bonita-layout.md
  md/profiles-overview.md
  md/release-notes.md
  md/technical-logging.md
  md/timers-execution.md
Labels: Review needed

#767 feat(Migration): Add a migration section on how to migrate to Java 11
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review needed

#764 RN(migration tool): update changelog for 2.40.x
  md/migration-tool.md
Labels: Ready to merge

#765 feat(release notes): add bug fixes
  md/release-notes.md
Labels: :construction: WIP :construction:

#773 feat(rest api): warning about ejb deprecation
  md/rest-api-overview.md
Labels: Review needed

#739 feat(documents) Tutorial to create a document validation process
  md/images/documentValidationProcess.png
  md/list-of-documents.md
Labels: Feedback integrated
