Repository bonitasoft/bonita-doc, pull requests merged in 2019-10, with the labels that each got.

#840 update BCD version link
  md/automating-builds.md
Labels: :shipit: Ready to merge :shipit:

#837 feat(releaseNote): Init release not for Bonita 7.9.4
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:, Review done

#882 doc(bdm-api): update description and title
  md/bdm-api.md
Labels: Review done

#819 chore(RN): add migration release note for 2.45.0
  md/migration-tool.md
Labels: :construction: WIP :construction:, :fire:Merge only on release :skull_and_crossbones:

#890 doc(deactivate-a-user): update description and title
  md/deactivate-a-user.md
Labels: Review done

#898 doc(bdm-in-rest-api): update description and title
  md/bdm-in-rest-api.md
Labels: Review done

#877 doc(naming conventions) update title and add description
  md/naming-conventions.md
Labels: Review done

#876 doc(actor and orga) update description
  md/organization-overview.md
Labels: Review done

#880 doc(pageName): Update description page bonita-bpm-studio-installation
  md/bonita-bpm-studio-installation.md
Labels: Review done

#884 doc(cases): Update description
  md/cases.md
Labels: Review done

#879 doc(connectivity-overview): Update
  md/connectivity-overview.md
Labels: Review done

#885 Update monitoring.md
  md/monitoring.md
Labels: Review done

#888 doc(pageName): Update description set-log-and-archive-levels
  md/set-log-and-archive-levels.md
Labels: Review done

#891 Update application-api.md
  md/application-api.md
Labels: Review done

#901 doc(pageName): Update description upgrade-from-community-to-a-subscription-edition
  md/upgrade-from-community-to-a-subscription-edition.md
Labels: Review done

#886 Update alfresco.md
  md/alfresco.md
Labels: Review done

#934 doc(pageName): Update description for page uze-gzip-compression
  md/use-gzip-compression.md
Labels: Review needed :book:

#1035 doc(rest-api-authentication): Update description
  md/rest-api-authentication.md
Labels: Review needed :book:

#1050 doc(pageName): Update description for page migrate-a-form-from-6-x
  md/migrate-a-form-from-6-x.md
Labels: Review needed :book:

#1052 doc(restore-default-look-feel): Update description and title
  md/restore-default-look-feel.md
Labels: Review needed :book:

#1019 doc(execution-sequence-states-and-transactions): update description and title
  md/execution-sequence-states-and-transactions.md
  md/taxonomy.md
Labels: Review needed :book:

#1008 doc(manage-the-platform): Update description
  md/manage-the-platform.md
Labels: Review needed :book:

#1057 doc(how-to): update title/description
  md/rta-mail-template.md
Labels: Review needed :book:

#1056 connector(sap-jco-3): update title and description
  md/sap-jco-3.md
Labels: Review needed :book:

#1055 connector(sap-jco-2): update title and description
  md/sap-jco-2.md
Labels: Review needed :book:

#1054 doc(managing-dependencies): update description and title
  md/managing-dependencies.md
Labels: Review needed :book:

#1001 doc(processes): Update description and title
  md/processes.md
Labels: Review needed :book:

#948 doc(tasks): Update description
  md/tasks.md
Labels: Review needed :book:

#946 doc(creating-a-new-look-feel): Update description and title
  md/creating-a-new-look-feel.md
Labels: Review needed :book:

#945 doc(pageName): Update description for page generate-pdf-from-an-office-document
  md/generate-pdf-from-an-office-document.md
Labels: Review needed :book:

#979 doc(portal-api): Update description and title
  md/portal-api.md
Labels: Review needed :book:

#933 doc(group): Update description and title
  md/group.md
Labels: Review needed :book:

#918 doc(automating-builds): update description and title
  md/automating-builds.md
Labels: Review needed :book:

#976 docr(twitterConnector)/Update description and title
  md/twitter.md
Labels: :-1: Change Needed :-1:

#829 fat(http): add info on http client connections
  md/configure-client-of-bonita-bpm-engine.md
  md/performance-tuning.md
  md/two-main-types-of-deployment.md
Labels: :fire:Merge only on release :skull_and_crossbones:, :shipit: Ready to merge :shipit:

#1010 doc(engine-architecture-overview): update description and title
  md/engine-architecture-overview.md
Labels: Review needed :book:

#996 doc(custom-user-information-in-bonita-bpm-studio): update description and title
  md/custom-user-information-in-bonita-bpm-studio.md
Labels: Review needed :book:

#998 doc(text annotations) Update text-annotations.md
  md/text-annotations.md
Labels: Review needed :book:

#977 doc(pageName): Update description for page import-and-export-a-process
  md/import-and-export-a-process.md
Labels: Review needed :book:

#927 doc(configurable-archive): update description and title
  md/configurable-archive.md
Labels: Review needed :book:

#988 doc(define-a-search-index): update description and title
  md/define-a-search-index.md
  md/taxonomy.md
Labels: Review done

#1002 doc(custom-user-information-in-bonita-bpm-portal): update description and title
  md/custom-user-information-in-bonita-bpm-portal.md
Labels: Review done

#951 doc(pageName): Update description for page insert-data-in-a-docx-odt-template
  md/insert-data-in-a-docx-odt-template.md
Labels: Review needed :book:

#943 doc(cache-configuration-and-policy) : Update description
  md/cache-configuration-and-policy.md
Labels: :-1: Change Needed :-1:, Review done

#968 doc(platform-api): Update description
  md/platform-api.md
Labels: Review needed :book:

#967 doc(configure-client-of-bonita-bpm-engine): update description and title
  md/configure-client-of-bonita-bpm-engine.md
Labels: Review needed :book:

#953 doc(identity-api): Update description and title
  md/identity-api.md
Labels: Review needed :book:

#994 doc(customuserinfo-api): Update description and title
  md/customuserinfo-api.md
Labels: Review needed :book:

#902 doc(documents): Update description
  md/documents.md
Labels: Review needed :book:

#957 doc(pageName): Update description for page two-main-types-of-deployment
  md/two-main-types-of-deployment.md
Labels: Review needed :book:

#962 doc(data-handling-overview): Update description and title
  md/data-handling-overview.md
Labels: Feedback integrated, Review done

#802 fix(Migration guide): add "RDBMS requirements" section + improve indentation
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review done

#975 doc(pageName): Update description for page environments
  md/environments.md
Labels: Review needed :book:

#922 doc(pageName): Update description ubuntu-openjdk-tomcat-postgresql
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Review needed :book:

#828 Getting started tutorial: English review and improvements
  md/bonita-studio-download-installation.md
  md/declare-business-variables.md
  md/declare-contracts.md
  md/define-business-data-model.md
  md/draw-bpmn-diagram.md
  md/what-is-bonita.md
Labels: Review needed :book:

#1064 fix(oracle): update grants for xa support
  md/database-configuration.md
Labels: Review needed :book:

#1062 doc(archive_maintenance): arch contract data maintenance description
  md/maintenance-operation.md
  md/taxonomy.md
Labels: Review needed :book:

#990 doc(variables) Update variables.md
  md/variables.md
Labels: Review needed :book:

#1067 fix(Migration): fix markup for warning message
  md/enforce-password-policy.md
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: :shipit: Ready to merge :shipit:

#1065 feat(deploy) update release note
  md/project_deploy_in_dev_suite.md
  md/release-notes.md
  md/taxonomy.md
Labels: Review done

#982 doc(create-your-first-project-with-the-engine-apis-and-maven): update description and title
  md/create-your-first-project-with-the-engine-apis-and-maven.md
Labels: :face_with_head_bandage: Change Needed

#1058 feat(postgres): document PostgreSQL performance tuning
  md/database-configuration.md
  md/performance-tuning.md
  md/release-notes.md
Labels: Feedback integrated, Review needed :book:

#1068 feat(R.N) Update release note to talk about the support of invalid XML char
  md/release-notes.md
Labels: :construction: WIP :construction:

#1063 doc(single-sign-on-with-cas): return URL addition
  md/single-sign-on-with-cas.md
Labels: Review done

#1060 doc(bonita layout) Add layout improvement to release note
  md/release-notes.md
Labels: Review needed :book:

#1000 feat(subtasks): remove documentation on subtasks
  md/administrator-rights.md
  md/subtasks.md
  md/taxonomy.md
  md/user-task-list.md
Labels: :heavy_check_mark: Question Answered, Feedback integrated, Review done

#1071 feat(installer) release note
  md/release-notes.md
Labels: Feedback integrated, Review done

#1070 feat(rn) add welcome page changes in RN
  md/release-notes.md
Labels: Review done

#1072 fix (SSO Kerberos) clarify and add troubleshooting note
  md/single-sign-on-with-kerberos.md
Labels: Review needed :book:

#1074 feat(connectors) notify deprecated connectors
  md/alfresco.md
  md/release-notes.md
Labels: :shipit: Ready to merge :shipit:

#1079 fix typo
  md/install-a-bonita-bpm-cluster.md
Labels: Review needed :book:

#1069 update images url path
  md/responsiveness-with-community-edition.md
Labels: Review done

#1066 tr(cleanup): remove useless WildFly module.xml files
  md/images/special_code/mysql/module.xml
  md/images/special_code/oracle/module.xml
  md/images/special_code/postgresql/module.xml
  md/images/special_code/sqlserver/module.xml
Labels: Review needed :book:

#1077 feat(utf8): Inform that we now support utf8mb4 encoding for Mysql.
  md/database-configuration.md
  md/release-notes.md
Labels: Review needed :book:

#1061 feature/addDeletionCase
  md/handling-documents.md
Labels: Review done

#1076 feat(BDM multi package) document multi package and merge features
  md/define-and-deploy-the-bdm.md
  md/release-notes.md
Labels: :face_with_head_bandage: Change Needed, Review done

#1080 feat(what is Bonita): add ACM capabilities
  md/what-is-bonita.md
Labels: :face_with_head_bandage: Change Needed, Review done

#1082 feat(ACM how to): promote project import in Studio
  md/use-bonita-acm.md
Labels: Feedback integrated, Review needed :book:

#1086 doc(index): create 7.10 content
  md/index.md
Labels: Review needed :book:
