Repository bonitasoft/bonita-doc, pull requests merged in 2019-09, with the labels that each got.

#808 feat(releaseNote): Init release not for Bonita 7.9.3
  md/release-notes.md
Labels: :construction: WIP :construction:, :fire:Merge only on release :skull_and_crossbones:

#812 chore(RN): add migration release note for 2.44.0
  md/migration-tool.md
Labels: Review needed

#811 feat(custom theme) Add how to create custom theme using bootswatch
  md/themes.md
Labels: Review done

#817 fix(getting-started): fix `info` typos and broken UI Designer icon
  md/configure-email-connector.md
  md/design-application-page.md
Labels: Review done

#818 feat(migration): add doc on verify script of migration
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: :shipit: Ready to merge :shipit:

#813 fix(7.9 rn): typo
  md/release-notes.md
Labels: :shipit: Ready to merge :shipit:

#768 Groovy in Bonita
  md/groovy-in-bonita.md
  md/taxonomy.md
Labels: :-1: Change Needed :-1:, Review done

#820 feat(monitoring): document platform monitoring
  md/engine-architecture-overview.md
  md/release-notes.md
  md/runtime-monitoring.md
  md/taxonomy.md
Labels: Feedback integrated, Review needed

#824 fix ssl version
  md/ssl.md
Labels: Review needed

#826 fix(requirements): specific supported OS versions
  md/hardware-and-software-requirements.md
Labels: Feedback integrated, Review done

#822 doc(widgets): Update description and title
  md/widgets.md
Labels: Review needed

#825 feat(XA setup): emphasis SQL Server restart
  md/database-configuration.md
Labels: Feedback integrated, Review needed

#814 fix(7.9 RN): add explicit limitation on edge
  md/release-notes.md
Labels: Review done

#810 fix(doc): fix incorrect information about BDM
  md/define-and-deploy-the-bdm.md
Labels: Review needed

#830 feat(acm) add how to enable acm plugin
  md/taxonomy.md
  md/use-bonita-acm.md
Labels: Feedback integrated, Review done

#831 howto/data-table-pagination-rest-api-extension
  md/widgets.md
Labels: Review done

#836 fix(typos): fix typos + colors
  md/contracts-and-contexts.md
Labels: Review needed :book:

#834 feat(ReleaseNote): Archiving Contract Data can now be disabled
  md/configurable-archive.md
  md/release-notes.md
Labels: Feedback integrated, Review done

#827 chore(Bundle): rename the bonita bundle from
  md/bonita-as-windows-service.md
  md/multi-tenancy-and-tenant-configuration.md
  md/release-notes.md
  md/sap-jco-3.md
  md/single-sign-on-with-cas.md
  md/tomcat-bundle.md
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Review done
