Repository bonitasoft/bonita-doc, pull requests merged in 2019-11, with the labels that each got.

#1085 feat(docker): Document usage of the Bonita docker image
  md/bonita-bpm-installation-overview.md
  md/bonita-docker-installation.md
  md/release-notes.md
  md/taxonomy.md
Labels: :heavy_check_mark: Question Answered, Feedback integrated, Review needed :book:

#1097 feat(guest user) update process start permissions mechanism
  md/guest-user.md
Labels: Feedback integrated

#1101 remove font-awesome reference from Bonita layout
  md/bonita-layout.md
Labels: Review done

#1102 fix(custom themes) remove reference to font awesome
  md/themes.md
Labels: Review done

#1090 doc(release-notes): removed libraries
  md/release-notes.md
Labels: Review needed :book:

#1099 fix(cas): remove reference to wildfly
  md/single-sign-on-with-cas.md
Labels: Review needed :book:

#1109 doc(DataManagement) Add documentation for data management
  md/ui-designer-overview.md
  md/variables.md
Labels: :construction: WIP :construction:

#1107 doc(tabContainer) doc new properties for dynamically tab container widget
  md/widgets.md
Labels: Review needed :book:

#1106 doc(tableWidget) How use new properties for Table and Data table widget
  md/widgets.md
Labels: Review needed :book:

#1105 feat(docker) improve docker documentation
  md/bonita-docker-installation.md
Labels: :face_with_head_bandage: Change Needed, Review done
