Repository bonitasoft/bonita-doc, pull requests merged in 2019-03, with the labels that each got.

#670 fix (License): add mandatory steps for installing a license
  md/licenses.md
Labels: Ready to merge

#649 fix(archiving): update the list of archivable elements
  md/configurable-archive.md
Labels: Review needed

#681 feat(release-notes): update to 7.8.3
  md/release-notes.md
Labels: Feedback integrated, Review needed

#682 feat(migration_tool_changlog): 2.39.0
  md/migration-tool.md
Labels: Ready to merge

#677 rn(form v6 removal): improve migration paths
  md/release-notes.md
Labels: Review needed

#667 feat(work): add page on work audit
  md/taxonomy.md
  md/work-execution-audit.md
Labels: Feedback integrated, Ready to merge

#666 feat(release): added logger for work execution audit
  md/release-notes.md
Labels: Ready to merge

#658 feat(adding): Adding an example of client configuration
  md/configure-client-of-bonita-bpm-engine.md
Labels: Review needed

#686 feat(Narayana): update documentation to reference Narayana (Arjuna)
  md/BonitaBPM_platform_setup.md
  md/bonita-as-windows-service.md
  md/database-configuration.md
  md/deploy-bundle.md
  md/hardware-and-software-requirements.md
  md/images/bonita-as-windows-service/bitronixConfiguration.png
  md/performance-tuning.md
  md/release-notes.md
  md/tomcat-bundle.md
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Feedback integrated, Question Answered, Review needed

#684 feat(ejb): add warnings about EJB deprecation
  md/configure-client-of-bonita-bpm-engine.md
  md/engine-api-overview.md
  md/performance-tuning.md
  md/two-main-types-of-deployment.md
Labels: Feedback integrated, Review done

#693 fix(doc): Remove debug mode in Studio
  md/environments.md
Labels: Ready to merge

#678 feat(performance): add details on quartz performance tunning
  md/performance-tuning.md
Labels: Feedback integrated, Review done

#691 feat(connector): add realease note + page on connectors
  md/connectors-execution.md
  md/images/connector_execution.png
  md/images/connector_execution_timeout.png
  md/release-notes.md
  md/taxonomy.md
Labels: Feedback integrated, Review done

#683 feat(ejb): add deprecation notice in release note
  md/release-notes.md
Labels: Feedback integrated, Review done

#699 feat(postgres 11): document the PostgreSQL version 11.2
  md/database-configuration.md
  md/hardware-and-software-requirements.md
  md/images/special_code/postgresql/module.xml
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/release-notes.md
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Review needed

#697 feat(oracle 12c): update documentation about Oracle 12c
  md/database-configuration.md
  md/hardware-and-software-requirements.md
  md/images/special_code/oracle/module.xml
  md/manage-users.md
Labels: Review needed

#692 fix(process documentation): wrong menu entry
  md/generate-process-documentation.md
Labels: Ready to merge

#700 Give more details about the default transition on inclusive gateway
  md/gateways.md
Labels: Review needed

#698 feat(timers): add details on timers and timers failure
  md/bpm-api.md
  md/release-notes.md
  md/timers-execution.md
Labels: Ready to merge, Review done

#694 feat(formGeneration) add info on constraint and error management
  md/contracts-and-contexts.md
  md/variables.md
Labels: Feedback integrated, Ready to merge

#703 Update Git trouble shooting section to talk about the issue with the two factor authentication
  md/share-a-repository-on-github.md
  md/workspaces-and-repositories.md
Labels: Feedback integrated
