Repository bonitasoft/bonita-doc, pull requests merged in 2019-01, with the labels that each got.

#645 Fix anchor for message API
  md/bpm-api.md
Labels: Question Asked

#647 fix(matrix) clarify java supported version
  md/hardware-and-software-requirements.md
Labels: Ready to merge, Review done

#646 fix(bar) process image not generated in bar
  md/release-notes.md
Labels: Change Needed, Review done

#648 fix(connector): typo in method list
  md/connectors-overview.md
Labels: Feedback integrated, Review needed

#650 feat(migtoolchangelog): add release 2.37.0
  md/migration-tool.md
Labels: Review needed

#652 feat(migtool changelog): add fix 2.37.0
  md/migration-tool.md
Labels: Ready to merge, Review done

#651 feat(RN): add release bug fixes 7.8.1
  md/release-notes.md
Labels: Ready to merge, Review done

#642 fix(web service) connector web service exemple v2
  .gitignore
  md/images/connector_webservice_tuto/webservice_diagram.png
  md/images/images-6_0/webservice_diagram.png
  md/web-service-tutorial.md
Labels: Feedback integrated, Review needed

#653 feat(UiPath): add missing documentation page
  md/taxonomy.md
  md/uipath.md
Labels: Review needed

#604 feat(v6 form removal): precise usage of v6 form removal
  md/release-notes.md
Labels: Feedback integrated, Rebase needed, Review needed

#655 fix(api): typo in example
  md/create-your-first-project-with-the-engine-apis-and-maven.md
Labels: Review needed
