Repository bonitasoft/bonita-doc, pull requests merged in 2019-07, with the labels that each got.

#783 feat(migration-tool): add 7.9.1 info
  md/migration-tool.md
Labels: Review needed

#782 feat(release notes): add 7.9.1 content
  md/release-notes.md
Labels: Feedback integrated, Review needed

#777 Add details about local env (cannot be shared)
  md/environments.md
Labels: Feedback integrated

#789 fix(doc): Clarify utf8mb4 is MySQL official reco
  md/release-notes.md
Labels: Ready to merge

#785 Fix/bpo 21 responsive feature for community
  md/images/responsiveness-community-edition/responsivenessCommunityEdition.PNG
  md/images/responsiveness-community-edition/responsivenessCommunityEditionOutput1.PNG
  md/images/responsiveness-community-edition/responsivenessCommunityEditionOutput2.PNG
  md/responsiveness-with-community-edition.md
  md/taxonomy.md
Labels: Ready to merge

#786 fix(doc): MySQL limitation UTF-8 (utfmb3)
  md/hardware-and-software-requirements.md
Labels: Review done

#787 Add trooblshooting section about installer JVM errors
  md/bonita-bpm-studio-installation.md
Labels: Review needed

#766 fix (doc) Add warning load balancer jvmRoute
  md/install-a-bonita-bpm-cluster.md
Labels: Review done

#794 feat(migration): Add the release note for migration tool 2.43.0
  md/migration-tool.md
Labels: Review needed
