Repository bonitasoft/bonita-doc, pull requests merged in 2019-05, with the labels that each got.

#721 feat(connectors): update doc on connector configuration
  md/performance-tuning.md
Labels: Change Needed

#725 feat(theme) theme development
  md/customize-living-application-theme.md
  md/taxonomy.md
Labels: Change Needed, Review done

#726 feat(default-layout) Deprecating the default layout in the documentation
  md/bonita-layout.md
  md/customize-application-layouts.md
  md/customize-living-application-layout.md
  md/layouts.md
  md/living-application-layout.md
  md/taxonomy.md
Labels: Review done

#731 feat(wildfly): deprecate the Wildfly bundle.
  md/deploy-bundle.md
  md/release-notes.md
  md/two-main-types-of-deployment.md
  md/wildfly-bundle.md
Labels: Change Needed, Review done

#734 doc(restApiExtension): clarify purpose of 'studio-internal-repository'
  md/rest-api-extensions.md
Labels: Review needed

#732 feat(bundles): update bundle names
  md/multi-tenancy-and-tenant-configuration.md
  md/release-notes.md
  md/tomcat-bundle.md
  md/ubuntu-openjdk-tomcat-postgresql.md
Labels: Review done

#736 Removing the need for an index.html file in the description of the theme
  md/themes.md
Labels: Review needed

#688 fix(rel_notes): v6 forms removal structure+wording
  md/release-notes.md
Labels: Review needed

#728 feat(Button) assign and execute task
  md/widgets.md
Labels: Review needed

#685 feat(data types): add "why" information
  md/create-a-complex-data-type.md
Labels: Feedback integrated, Review needed

#733 feat(packaging): Deploy Bundle removal & cas & LDAP synchronizer move
  md/BonitaBPM_platform_setup.md
  md/bonita-as-windows-service.md
  md/bonita-bpm-installation-overview.md
  md/configure-client-of-bonita-bpm-engine.md
  md/deploy-bundle.md
  md/ldap-synchronizer.md
  md/licenses.md
  md/release-notes.md
  md/single-sign-on-with-cas.md
  md/tomcat-bundle.md
  md/ubuntu-openjdk-tomcat-postgresql.md
  md/wildfly-bundle.md
Labels: Rebase needed, Review needed

#741 connector(script): document Windows usage
  md/script.md
Labels: Review needed

#735 Renamed the customize resource layouts to remove resource
  md/customize-layouts.md
  md/living-application-layout.md
  md/taxonomy.md
Labels: Review needed

#744 feat(Java11): add clarification on Java 11 compatibility/behaviour.
  md/release-notes.md
Labels: Ready to merge, Review done

#748 feat(Arjuna): Indicate that tomcat+Sql Server works in 7.9.0
  md/database-configuration.md
  md/hardware-and-software-requirements.md
  md/tomcat-bundle.md
Labels: Review needed

#750 feat(Arjuna): Add link to configuration in the release note
  md/release-notes.md
Labels: Review needed

#751 feat(Tomcat): Update the Tomcat version in Hardware&Software req
  md/hardware-and-software-requirements.md
Labels: Review needed

#746 fix(release-notes): reorder and reword
  md/release-notes.md
Labels: Review needed

#754 doc(index): add 7.9 content
  md/index.md
Labels: WIP

#756 doc(RN): retrieve missing runtime items
  md/release-notes.md
Labels: Review needed

#749 Adding information in forms about the view in application feature
  md/forms.md
Labels: Review needed
