Repository bonitasoft/bonita-doc, pull requests merged in 2019-08, with the labels that each got.

#795 add(release notes): 7.9.2 first iteration
  md/release-notes.md
Labels: Feedback integrated, Review needed

#727 fix(deployment): bonita portal as remote client of the bonita engine
  md/configure-client-of-bonita-bpm-engine.md
  md/two-main-types-of-deployment.md
Labels: Feedback integrated, Review done

#798 feat(deployZip removal): remove last references to deploy/bundle zip
  md/bonita-bpm-installation-overview.md
  md/custom-deployment.md
  md/database-configuration.md
  md/install-a-bonita-bpm-cluster.md
  md/taxonomy.md
Labels: Review done

#793 feat(Wildfly): Remove the Wildfly bundle from documentation
  md/BonitaBPM_platform_setup.md
  md/active-directory-or-ldap-authentication.md
  md/api-extensions.md
  md/back-up-bonita-bpm-platform.md
  md/bonita-bpm-installation-overview.md
  md/cluster-administration.md
  md/configure-client-of-bonita-bpm-engine.md
  md/custom-deployment.md
  md/database-configuration.md
  md/engine-api-overview.md
  md/first-steps-after-setup.md
  md/hardware-and-software-requirements.md
  md/images/images-6_0/dev_overview_api_access.png
  md/install-a-bonita-bpm-cluster.md
  md/languages.md
  md/ldap-synchronizer.md
  md/licenses.md
  md/log-files.md
  md/logging.md
  md/pages.md
  md/performance-tuning.md
  md/release-notes.md
  md/rest-api-overview.md
  md/sap-jco-3.md
  md/single-sign-on-with-cas.md
  md/single-sign-on-with-kerberos.md
  md/single-sign-on-with-saml.md
  md/ssl.md
  md/taxonomy.md
  md/tenant_admin_credentials.md
  md/tomcat-bundle.md
  md/two-main-types-of-deployment.md
  md/use-gzip-compression.md
  md/wildfly-bundle.md
Labels: :-1: Change Needed :-1:, Review done

#796 feat(EJB removal): state that ejb support has been removed
  md/performance-tuning.md
  md/release-notes.md
Labels: :cry: Rebase needed :cry:, Based on another PR

#792 feat (custom page debug mode) document studio behavior
  md/api-extensions.md
  md/pages.md
Labels: Feedback integrated, Review done

#801 fix(migration): add detailed oracle migration step
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/release-notes.md
Labels: :shipit: Ready to merge :shipit:

#774 feat(SEO): update a few page descriptions
  md/bonita-bpm-studio-hints-and-tips.md
  md/cluster-administration.md
  md/create-administration-tools.md
Labels: Feedback integrated, Review needed

#784 fix(doc): fix incorrect configuration keys
  md/configurable-archive.md
Labels: Review needed

#799 feat(wildfly removal): remove references to WildFly
  md/two-main-types-of-deployment.md
Labels: Review needed

#800 fix(mysql): MySQL 8.x IS supported in 7.9+ versions
  md/hardware-and-software-requirements.md
Labels: Review needed

#806 build(bonita): simplify documentation
  md/building-community-edition-from-source.md
Labels: :shipit: Ready to merge :shipit:, Review done

#805 fix(migration): specify Oracle 12c 12.2.x.y
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review needed

#804 fix(rn): Oracle 12c spec at each line (12.2.x.y)
  md/release-notes.md
Labels: Review needed
