Repository bonitasoft/bonita-doc, pull requests merged in 2020-01, with the labels that each got.

#1122 fix(REST API) document delete process with warning
  md/bpm-api.md
Labels: Review needed :book:

#1124 doc(SAML) Hash URL parameters lost in redirections
  md/single-sign-on-with-saml.md
Labels: Review needed :book:

#1125 doc(wildfly): document WildFly to Tomcat conversion
  md/convert-wildfly-into-tomcat.md
  md/release-notes.md
  md/taxonomy.md
Labels: Review needed :book:

#1130 Fix typo and add gif
  md/draw-bpmn-diagram.md
  md/images/getting-started-tutorial/draw-bpmn-diagram/new-diagram.gif
Labels: Review done

#1128 Review and update of getting started
  md/bonita-studio-download-installation.md
  md/images/getting-started-tutorial/installation/studio-first-start-01-welcome-popup-values.png
  md/images/getting-started-tutorial/installation/studio-first-start-02-studio-on-welcome-page.png
  md/what-is-bonita.md
Labels: Feedback integrated, Review done

#1129 Fix issue with display of large images
  md/bonita-studio-download-installation.md
  md/what-is-bonita.md
Labels: :shipit: Ready to merge :shipit:, Review done

#1145 fix(rest): remove ejb from architecture overview
  md/images/images-6_0/rest_overview_v2.png
  md/images/rest_api_architecture_overview.png
  md/rest-api-overview.md
Labels: Review needed :book:
