Repository bonitasoft/bonita-doc, pull requests merged in 2020-05, with the labels that each got.

#1217 fix(out-of-date doc): fix Engine API example doc
  md/manage-a-process.md
Labels: Review needed :book:

#1216 doc(release notes): portal transformation info
  md/release-notes.md
Labels: Feedback integrated, Review done

#1226 chore(formatting): fix bad formatting of paragraph (base 7.7)
  md/engine-architecture-overview.md
  md/generate-pdf-from-an-office-document.md
  md/resource-management.md
  md/using-list-and-search-methods.md
Labels: Review needed :book:

#1225 chore(formatting): fix bad formatting of paragraph (for 7.10+)
  md/database-configuration.md
Labels: Review needed :book:

#1223 feat(index): create page content
  md/index.md
  md/release-notes.md
Labels: :construction: WIP :construction:

#1236 feat(oracle): The oracle driver will now comes packaged in the bundle.
  md/BonitaBPM_platform_setup.md
  md/custom-deployment.md
  md/database-configuration.md
  md/hardware-and-software-requirements.md
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/release-notes.md
  md/tomcat-bundle.md
Labels: Review needed :book:

#1234 fix(logs): remove ref to removed log files
  md/log-files.md
  md/logging.md
Labels: Review needed :book:
