Repository bonitasoft/bonita-doc, pull requests merged in 2020-11, with the labels that each got.

#1322 Update release-notes.md
  md/release-notes.md
Labels: 7.11.3

#1323 chore(searrchKey): add search key in release note
  md/bpm-api.md
  md/cases.md
  md/execution-sequence-states-and-transactions.md
  md/operations.md
  md/pools-and-lanes.md
  md/refactoring.md
  md/release-notes.md
  md/rest-api-overview.md
Labels: Review needed :book:

#1336 feat(recovery): add doc on fault telorance mechanisms
  md/fault-tolerance.md
  md/release-notes.md
  md/tasks.md
  md/taxonomy.md
Labels: Review needed :book:

#1337 feat(RN): Notifies that micrometer has been updated.
  md/release-notes.md
Labels: Review needed :book:

#1326 doc(uid) List dependencies for version 7.11
  md/ui-designer-dependencies.md
Labels: :warning: Do not merge :warning:

#1325 doc(uid) List dependencies for version 7.12
  md/ui-designer-dependencies.md
Labels: :warning: Do not merge :warning:

#1343 feat(recovery): update doc with Engine recent changes
  md/fault-tolerance.md
Labels: Review needed :book:

#1342 doc(releaseNote): prepare 7.11.4
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:

#1349 chore (release-note) clarify the login changes in 7.12
  md/release-notes.md
Labels: Review needed :book:

#1350 fix(log): explain how to enable BONITA WORK AUDIT
  md/work-execution-audit.md
Labels: Review needed :book:
