Repository bonitasoft/bonita-doc, pull requests merged in 2020-02, with the labels that each got.

#1141 Update getting started application creation
  md/create-application.md
  md/images/getting-started-tutorial/create-application/application-page-deployment.png
  md/images/getting-started-tutorial/create-application/project-deployment.gif
Labels: Review needed :book:

#1139 Update getting started connector configuration page
  md/configure-email-connector.md
Labels: Review needed :book:

#1140 Update getting started application page creation
  md/design-application-page.md
  md/images/getting-started-tutorial/design-application-page/data-model.png
  md/images/getting-started-tutorial/design-application-page/declare-claims-page-variable.gif
Labels: Review needed :book:

#1143 doc(SAML) improve encrypted assertions doc
  md/single-sign-on-with-saml.md
Labels: Review needed :book:

#1134 Init release note for version 7.10.1
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:, Review done

#1136 feat(documentation) doc generation
  md/images/doc-generation/export_as_pdf.png
  md/images/doc-generation/generate_doc_menu.png
  md/images/doc-generation/github_preview.png
  md/images/doc-generation/pdfIcon.png
  md/images/doc-generation/previewHTML.png
  md/project-documentation-generation.md
  md/taxonomy.md
Labels: :construction: WIP :construction:

#1155 fix(oracle): Add that we support Oracle 19c
  md/database-configuration.md
  md/hardware-and-software-requirements.md
Labels: :construction: WIP :construction:

#1165 feat(Additional resources) add documentation on additional resources
  md/additional-resources.md
  md/release-notes.md
  md/taxonomy.md
Labels: Review needed :book:
