Repository bonitasoft/bonita-doc, pull requests merged in 2020-12, with the labels that each got.

#1334 add(support-uid-troubleshooting): Create page
  md/images/how-to.png
  md/images/troubleshooting.png
  md/images/ui-designer-troubleshooting/404-error-chrome.png
  md/images/ui-designer-troubleshooting/ff-blank-page.png
  md/images/ui-designer-troubleshooting/uid-logs.png
  md/ui-designer-overview.md
Labels: :shipit: Ready to merge :shipit:, Review done

#1341 GA 7.12 Release Notes
  md/release-notes.md
Labels: :construction: WIP :construction:

#1360 doc(connectors): document connector config in case of failure
  md/connectivity-overview.md
Labels: Review needed :book:

#1359 doc(BDM): document 7.12 BDM ID generation with Hibernate
  md/release-notes.md
Labels: :shipit: Ready to merge :shipit:, Review done
