Repository bonitasoft/bonita-doc, pull requests merged in 2020-06, with the labels that each got.

#1206 chore(release-note): 7.10.5 release note
  md/release-notes.md
Labels: :construction: WIP :construction:, :fire:Merge only on release :skull_and_crossbones:

#1231 doc(data_management) : New Data Management page
  md/data-management.md
  md/images/data_model_panel.png
  md/images/uid_data_management_wizard.png
  md/images/uid_data_model_panel.png
  md/images/uid_graphql_voyager.png
  md/taxonomy.md
  md/variables.md
Labels: :shipit: Ready to merge :shipit:, Review done

#1247 feat(release-note) URL encode document name
  md/bpm-api.md
  md/list-of-documents.md
  md/release-notes.md
Labels: Review done

#1253 update (release notes): add IE11 support deprec
  md/release-notes.md
Labels: Review needed :book:

#1244 doc(releaseNote) improve style
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:

#1255 fix(RN): fix minor issues within Release Notes page
  md/release-notes.md
Labels: Review needed :book:

#1254 doc(RN): backport Migration Tool changelog back to 7.8
  md/migration-tool.md
Labels: Review needed :book:

#1252 update(index): add archetype, fix uiPath
  md/index.md
Labels: Review needed :book:
