Repository bonitasoft/bonita-doc, pull requests merged in 2020-10, with the labels that each got.

#1279 feat(engine): review taxonomy of engine dev doc
  md/taxonomy.md
Labels: Review needed :book:

#1282 feat(theme): Introduce theme archetype
  md/customize-living-application-theme.md
Labels: :warning: Do not merge :warning:

#1283 feat(dev-doc): add developer doc on works
  md/taxonomy.md
  md/work-execution.md
  md/work-locking.md
Labels: Review done

#1285 feat(dev-doc): add developer doc on execution of elements
  md/how-a-flownode-is-completed.md
  md/how-a-flownode-is-executed.md
  md/how-a-process-is-completed.md
  md/taxonomy.md
Labels: Review needed :book:

#1289 format(typo): minor typo fixes
  md/release-notes.md
Labels: Review needed :book:

#1284 feat(dev-doc): add developer doc flow node stats
  md/engine-flow-node-states.md
  md/taxonomy.md
Labels: Review done

#1292 feat(indexes): search indexes or no more subscription
  md/bpm-api.md
  md/define-a-search-index.md
  md/execution-sequence-states-and-transactions.md
  md/refactoring.md
Labels: Review needed :book:

#1297 Update (doc): add how-to information to diagram-tasks.md
  md/diagram-tasks.md
Labels: hacktoberfest-accepted

#1306 fix(actors): add candidate and assignee definition
  md/actors.md
Labels: Review needed :book:

#1309 Update de la page d'intro - terminologie
  md/bonita-bpm-overview.md
  md/taxonomy.md
  md/tutorial-overview.md
  md/what-is-bonita.md
Labels: :shipit: Ready to merge :shipit:, Review done

#1291 fix(doc): more details and fixes
  md/bonita-as-windows-service.md
Labels: Review needed :book:

#1313 doc(login) redirect parameter is now optional in 7.12
  md/multi-tenancy-and-tenant-configuration.md
  md/platform-api.md
  md/release-notes.md
  md/rest-api-authentication.md
  md/rest-api-overview.md
Labels: Review needed :book:

#1318 doc(SSO configuration): update Kerberos and SAML configuration
  md/single-sign-on-with-kerberos.md
  md/single-sign-on-with-saml.md
Labels: Feedback integrated, Review needed :book:
