Repository bonitasoft/bonita-doc, pull requests merged in 2020-03, with the labels that each got.

#1183 feat(ReleaseNote): Release note 7.9.5 with the Oracle + Tomcat bug.
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:, Review needed :book:

#1184 feat(ReleaseNote): Release note 7.10.3 with the Oracle + Tomcat bug.
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:, Review needed :book:

#1175 doc(monitoring): add doc on new messages matching metrics
  md/runtime-monitoring.md
Labels: :fire:Merge only on release :skull_and_crossbones:, Review done

#1188 fix(release notes): release dates
  md/release-notes.md
Labels: Review needed :book:

#1163 chore(dependencies): Adding Ui-designer dependencies report for the v…
  md/ui-designer-dependencies.md
Labels: :construction: WIP :construction:

#1177 Update uid-case-overview-tutorial.md
  md/uid-case-overview-tutorial.md
Labels: :cry: Rebase needed :cry:, :heavy_check_mark: Question Answered, Review done

#1073 doc(archiving): rename Bonita Platform => Runtime
  md/maintenance-operation.md
  md/taxonomy.md
Labels: :heavy_check_mark: Question Answered, Review needed :book:

#1194 fix(maintenance): fix typos and formulating
  md/maintenance-operation.md
Labels: Review needed :book:

#1202 Remove unexisting screenshot
  md/bonita-studio-download-installation.md
Labels: :shipit: Ready to merge :shipit:, :warning: CLA not signed
