Repository bonitasoft/bonita-doc, pull requests merged in 2020-07, with the labels that each got.

#1258 fix(doc) manually trigger cache busting meaning
  md/live-update.md
Labels: :face_with_head_bandage: Change Needed, Review done

#1262 feat(queries): document slow queries logging threshold
  md/performance-troubleshooting.md
Labels: Review done

#1250 feat: add doc on warning for long connectors
  md/performance-troubleshooting.md
  md/performance-tuning.md
Labels: Review done

#1246 feat(hardware-software): Increase sqlversion to 2017
  md/hardware-and-software-requirements.md
Labels: :question: Question Asked :question:

#1268 doc(uid) List dependencies for version 7.11
  md/ui-designer-dependencies.md
Labels: :construction: WIP :construction:
