Repository bonitasoft/bonita-doc, pull requests merged in 2020-04, with the labels that each got.

#1198 RN(7.10.4): write bug fix list for 7.10.4 release
  md/migration-tool.md
  md/release-notes.md
Labels: :fire:Merge only on release :skull_and_crossbones:, :shipit: Ready to merge :shipit:, Review done

#1200 Create release note for migration tool 2.50.0
  md/migration-tool.md
Labels: :fire:Merge only on release :skull_and_crossbones:, :shipit: Ready to merge :shipit:, Review done

#1203 feat(Case Overview): explain new migration mode to update Case Overview pages
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/migration-tool.md
Labels: Review needed :book:

#1204 tr(asciinema): host our own asciinema files & player
  md/images/case_overview_update_mode-ascii.cast
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review needed :book:

#1208 fix(db config): API case-insensitive searches
  md/database-configuration.md
Labels: Review needed :book:

#1207 feat(RN&Migration): No migration for Maintenance versions
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
  md/release-notes.md
Labels: Feedback integrated
