Repository bonitasoft/bonita-doc, pull requests merged in 2021-07, with the labels that each got.

#1607 update(release notes): add video links
  modules/ROOT/pages/release-notes.adoc
Labels: Learning, Review done

#1512 fix(rn): Provide a way to clean duplicated foreign keys
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#1583 Update(ldap connector): add troubleshooting
  modules/ROOT/pages/ldap.adoc
Labels: Learning, Review needed :book:

#1616 chore: update windows service install guide
  modules/ROOT/assets/images/images/bonita-as-windows-service/bonitaXml.png
  modules/ROOT/pages/bonita-as-windows-service.adoc
  modules/ROOT/pages/database-configuration.adoc
Labels: Review done

#1604 update(ssl): add troubleshooting section
  modules/ROOT/pages/ssl.adoc
Labels: :question: Question Asked :question:, Learning, Review done

#1619 Update(studio-git): add troubleshooting proxy settings
  modules/ROOT/pages/bonita-bpm-studio-preferences.adoc
  modules/ROOT/pages/workspaces-and-repositories.adoc
Labels: Review needed :book:

#1618 update(SAML SSO): format troubleshooting section
  modules/ROOT/pages/single-sign-on-with-saml.adoc
Labels: Review done

#1579 fix(BDM): Update the BDM doc to include new API methods
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
Labels: Feedback integrated, Review needed :book:

#1590 2021.2 Release Notes
  modules/ROOT/pages/release-notes.adoc
Labels: :warning: Do not merge :warning:

#1624 fix(cust_auth): file name with an 's' bonita-tenants-custom.xml
  modules/ROOT/pages/custom-authorization-rule-mapping.adoc
Labels: Review needed :book:

#1621 Update(what-is-bonita-index.adoc): adjust to real content
  modules/ROOT/pages/what-is-bonita-index.adoc
Labels: :shipit: Ready to merge :shipit:

#1625 Update bonita-studio.adoc
  modules/ROOT/pages/bonita-studio.adoc
Labels: Review needed :book:

#1620 update(api-index): add all content
  modules/ROOT/pages/api-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: :face_with_head_bandage: Change Needed

#1623 update(getting started): fill out the todo, fix first page
  modules/ROOT/pages/getting-started-index.adoc
  modules/ROOT/pages/tutorial-overview.adoc
Labels: Feedback integrated, Review needed :book:

#1622 Update(bonita-bpm-overview): Remove inadequate content and add cards
  modules/ROOT/pages/bonita-bpm-overview.adoc
  modules/ROOT/taxonomy.adoc
Labels: Feedback integrated, Review needed :book:

#1589 fix(links): fix links that were valid in the previous doc
  modules/ROOT/pages/living-application-layout.adoc
  modules/ROOT/pages/rest-api-extensions.adoc
  modules/ROOT/pages/single-sign-on-with-kerberos.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/tomcat-bundle.adoc
Labels: Review needed :book:

#1634 Update taxonomy.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1636 doc(dependencies): list all dependency pages
  modules/ROOT/pages/dependencies-index.adoc
Labels: Review needed :book:

#1611 doc(transactions): detail the transactions at API level
  modules/ROOT/pages/execution-sequence-states-and-transactions.adoc
Labels: Review needed :book:

#1639 Update (BonitaBPM_platform_setup.adoc): rename
  modules/ROOT/pages/bonita-bpm-platform-setup.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1642 Update and rename applicationCreation.adoc to application-creation.adoc
  modules/ROOT/pages/application-creation.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1643 Rename profileCreation.adoc in 7.9
  modules/ROOT/pages/profile-creation.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1646 feat(com/ent upgrade): Change where to check the upgrade
  modules/ROOT/pages/upgrade-from-community-to-a-subscription-edition.adoc
Labels: Review needed :book:

#1631 Update project-best-practices-index.adoc
  modules/ROOT/pages/project-best-practices-index.adoc
Labels: Feedback integrated, Review needed :book:

#1587 fix(links): fix links that were valid in the previous doc
  modules/ROOT/pages/cases.adoc
  modules/ROOT/pages/define-business-data-model.adoc
  modules/ROOT/pages/guest-user.adoc
  modules/ROOT/pages/single-sign-on-with-kerberos.adoc
  modules/ROOT/pages/special-users.adoc
Labels: Based on another PR

#1615 update(actor-index): update cards and sections
  modules/ROOT/pages/actors-index.adoc
  modules/ROOT/pages/getting-started-index.adoc
Labels: Feedback integrated, Review needed :book:

#1640 fix(diagram index): add card descriptions
  modules/ROOT/pages/diagram-overview.adoc
  modules/ROOT/pages/diagrams-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1648 chore(renaming): rename referencing pages
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/bdm-access-control.adoc
  modules/ROOT/pages/bonita-bpm-installation-overview.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/configurable-archive.adoc
  modules/ROOT/pages/csrf-security.adoc
  modules/ROOT/pages/custom-deployment.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/embed-engine.adoc
  modules/ROOT/pages/enforce-password-policy.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/event-handlers.adoc
  modules/ROOT/pages/first-steps-after-setup.adoc
  modules/ROOT/pages/install-a-bonita-bpm-cluster.adoc
  modules/ROOT/pages/licenses.adoc
  modules/ROOT/pages/manage-the-platform.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
  modules/ROOT/pages/pages.adoc
  modules/ROOT/pages/performance-tuning.adoc
  modules/ROOT/pages/queriable-logging.adoc
  modules/ROOT/pages/resource-management.adoc
  modules/ROOT/pages/rest-api-authorization.adoc
  modules/ROOT/pages/set-log-and-archive-levels.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/tomcat-bundle.adoc
  modules/ROOT/pages/upgrade-from-community-to-a-subscription-edition.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
  modules/ROOT/pages/using-list-and-search-methods.adoc
  modules/ROOT/pages/wildfly-bundle.adoc
Labels: Review needed :book:

#1600 refactor(BDM): move BDM limitations to another page
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
  modules/ROOT/taxonomy.adoc
Labels: Feedback integrated, Review needed :book:
