Repository bonitasoft/bonita-doc, pull requests merged in 2021-03, with the labels that each got.

#1419 update(index): Card description
  modules/ROOT/pages/index.adoc
Labels: Feedback integrated, Review needed :book:, newDocSite

#1344 doc(events): add constraint to event handlers implementation
  md/event-handlers.md
Labels: Review done

#1345 doc(recovery): add more info on recovery metrics and conf
  md/fault-tolerance.md
Labels: :question: Question Asked :question:

#1400 7.12.1 work delay xa sqlserver
  md/performance-tuning.md
Labels: :face_with_head_bandage: Change Needed, Review done

#1371 feat(docker): how to run bonita container interactively
  md/bonita-docker-installation.md
Labels: docker

#1423 feat(upgrade): notify the easier upgrade in RN
  md/release-notes.md
  md/upgrade-from-community-to-a-subscription-edition.md
Labels: Review needed :book:

#1361 chore(release): prepare release note 7.13
  md/release-notes.md
Labels: Review done

#1426 feat(JAAS in SP): move JAAS implem to SP only
  md/release-notes.md
Labels: Review done

#1437 feat(upgrade): emphasize to Stop Tomcat before removing the WAR
  md/upgrade-from-community-to-a-subscription-edition.md
Labels: Review needed :book:

#1440 fix(oidc): add 'setup pull' step and fix typos
  md/single-sign-on-with-oidc.md
Labels: Review needed :book:

#1151 fix(migration): detail the Oracle version change
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: :face_with_head_bandage: Change Needed, Review done

#1381 update(migration): Contraints indexes
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: :cry: Rebase needed :cry:

#1401 Removed Expression Types
  md/expressions-and-scripts.md
  md/transitions.md
Labels: :cry: Rebase needed :cry:, Review needed :book:

#1441 fix(migration): Warn about not stopping BPM services before migrating.
  md/migrate-from-an-earlier-version-of-bonita-bpm.md
Labels: Review needed :book:

#1439 feat: improve the bonita archives page
  README.md
  antora.yml
  modules/ROOT/pages/archives.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/taxonomy.adoc
Labels: :construction: WIP :construction:, newDocSite

#1456 fix(7.11): set ref to getting started in index page
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1458 Fix declare-business-variables.adoc
  modules/ROOT/pages/declare-business-variables.adoc
Labels: Review done

#1448 fix(2021.1): update links to javadoc
  antora.yml
  modules/ROOT/pages/api-glossary.adoc
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/ROOT/pages/connectors-overview.adoc
  modules/ROOT/pages/create-administration-tools.adoc
  modules/ROOT/pages/creating-an-actor-filter.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/engine-api-overview.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/groovy-in-bonita.adoc
  modules/ROOT/pages/handle-a-failed-activity.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/ldap.adoc
  modules/ROOT/pages/manage-users.adoc
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
  modules/ROOT/pages/pause-and-resume-bpm-services.adoc
  modules/ROOT/pages/performance-troubleshooting.adoc
  modules/ROOT/pages/queriable-logging.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
  modules/ROOT/pages/using-list-and-search-methods.adoc
  modules/ROOT/taxonomy.adoc
Labels: :heavy_check_mark: Question Answered, Review needed :book:

#1470 fix(icon): remove usage of unsupported font awesome icons
  antora.yml
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/bonita-bpm-portal-interface-overview.adoc
  modules/ROOT/pages/bonita-bpm-portal-urls.adoc
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/generate-pdf-from-an-office-document.adoc
  modules/ROOT/pages/live-update.adoc
  modules/ROOT/pages/living-application-layout.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/rta-mail-template.adoc
  modules/ROOT/pages/widgets.adoc
Labels: Review needed :book:

#1472 fix: fix asciidoctor warnings and errors
  modules/ROOT/pages/bonita-bpm-overview.adoc
  modules/ROOT/pages/building-community-edition-from-source.adoc
  modules/ROOT/pages/maintenance-operation.adoc
  modules/ROOT/pages/manage-a-process.adoc
  modules/ROOT/pages/share-a-repository-on-github.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
Labels: Review needed :book:

#1471 fix: ensure that asciidoc attributes are expanded correctly
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
  modules/ROOT/pages/api-glossary.adoc
  modules/ROOT/pages/application-api.adoc
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/ROOT/pages/connectors-overview.adoc
  modules/ROOT/pages/create-administration-tools.adoc
  modules/ROOT/pages/create-your-first-project-with-the-engine-apis-and-maven.adoc
  modules/ROOT/pages/creating-an-actor-filter.adoc
  modules/ROOT/pages/custom-authorization-rule-mapping.adoc
  modules/ROOT/pages/customuserinfo-api.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/engine-api-overview.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/event-handlers.adoc
  modules/ROOT/pages/groovy-in-bonita.adoc
  modules/ROOT/pages/handle-a-failed-activity.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/ldap.adoc
  modules/ROOT/pages/manage-users.adoc
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
  modules/ROOT/pages/pause-and-resume-bpm-services.adoc
  modules/ROOT/pages/performance-troubleshooting.adoc
  modules/ROOT/pages/queriable-logging.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
  modules/ROOT/pages/using-list-and-search-methods.adoc
Labels: Review needed :book:

#1475 fix(7.11): use correct admonitions syntax and fix some typos
  modules/ROOT/pages/bonita-as-windows-service.adoc
Labels: Review needed :book:

#1476 fix(7.9): set meaningful description in access-control-api
  modules/ROOT/pages/access-control-api.adoc
Labels: :sunflower: Non Bonitasoft Contribution, Review needed :book:

#1469 Update(queriable-logging): how to disable
  modules/ROOT/pages/queriable-logging.adoc
Labels: :construction: WIP :construction:, Learning, Review needed :book:

#1489 fix(version): put technical version where branding version was used
  modules/ROOT/pages/create-your-first-project-with-the-engine-apis-and-maven.adoc
  modules/ROOT/pages/custom-authorization-rule-mapping.adoc
  modules/ROOT/pages/event-handlers.adoc
Labels: Review needed :book:

#1487 fix(7.9): fix table in bonita bpm portal urls page
  modules/ROOT/pages/bonita-bpm-portal-urls.adoc
Labels: :shipit: Ready to merge :shipit:

#1490 chore(2021.1): introduce a 'bonitaTechnicalVersion' attribute
  antora.yml
  modules/ROOT/pages/create-your-first-project-with-the-engine-apis-and-maven.adoc
  modules/ROOT/pages/custom-authorization-rule-mapping.adoc
  modules/ROOT/pages/event-handlers.adoc
Labels: Review done

#1488 feat(OIDC): Support non JWT access tokens
  modules/ROOT/assets/images/images/OIDC-overview.png
  modules/ROOT/pages/single-sign-on-with-oidc.adoc
Labels: Feedback integrated

#1499 chore(2021.1): fix bonita version attributes substitution
  antora.yml
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/bonita-studio-download-installation.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
Labels: :heavy_check_mark: Question Answered, Review done

#1500 format(style): fix various WARNING messages
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/organization-management-in-bonita-bpm-studio.adoc
  modules/ROOT/pages/uid-vertical-tabs-container-tutorial.adoc
Labels: Feedback integrated, Review done

#1479 chore(deps 7.11): convert engine dependencies report to asciidoc
  modules/ROOT/pages/bonita-engine-dependencies.adoc
Labels: :shipit: Ready to merge :shipit:, Review done

#1480 chore(deps 7.12): convert engine dependencies report to asciidoc
  .gitattributes
  modules/ROOT/pages/bonita-engine-dependencies.adoc
Labels: Review needed :book:

#1497 feat(index): add desc to the RN topics cards
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1503 fix(index): shorten descriptions
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1494 fix(7.9): fix broken links
  modules/ROOT/pages/api-glossary.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/connectors-overview.adoc
  modules/ROOT/pages/data-handling-overview.adoc
  modules/ROOT/pages/database-configuration.adoc
  modules/ROOT/pages/first-steps-after-setup.adoc
  modules/ROOT/pages/list-of-documents.adoc
  modules/ROOT/pages/manage-control-in-forms.adoc
  modules/ROOT/pages/multi-language-pages.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/ROOT/pages/set-up-kpis.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/tomcat-bundle.adoc
  modules/ROOT/pages/variables.adoc
  modules/ROOT/pages/wildfly-bundle.adoc
Labels: Review needed :book:

#1492 fix(product-versioning): use code example instead of screenshot
  modules/ROOT/assets/images/images/Modelversion-example.png
  modules/ROOT/pages/product-versioning.adoc
Labels: Review needed :book:

#1498 feat(index): add cards description
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1502 feat(OIDC): support all target URLs
  modules/ROOT/assets/images/images/oidc-overview.png
  modules/ROOT/pages/single-sign-on-with-oidc.adoc
Labels: Review done
