Repository bonitasoft/bonita-doc, pull requests merged in 2021-08, with the labels that each got.

#1650 feat(bdm): update the bdm limitations doc to give more details about he different cases
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
Labels: Review needed :book:

#1651 feat(RN): deprecate the ReportingAPI
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1655 feat(RN): create RN for 7.12.7
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1649 Update documents section
  modules/ROOT/pages/documents-index.adoc
  modules/ROOT/pages/documents.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1638 Update design-methodology.adoc
  modules/ROOT/assets/images/images/project phases.png
  modules/ROOT/pages/design-methodology.adoc
  modules/ROOT/pages/lifecycle-and-profiles.adoc
Labels: Review needed :book:

#1633 Update setup-dev-environment-index.adoc
  modules/ROOT/pages/setup-dev-environment-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: :question: Question Asked :question:, Review needed :book:, Feedback integrated

#1645 Update create-or-modify-a-page.adoc
  modules/ROOT/pages/create-or-modify-a-page.adoc
  modules/ROOT/pages/forms-development.adoc
  modules/ROOT/pages/forms.adoc
  modules/ROOT/pages/page-and-form-development-overview.adoc
  modules/ROOT/pages/pages-and-forms.adoc
  modules/ROOT/pages/pages-development.adoc
  modules/ROOT/pages/pages.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:, Feedback integrated

#1667 feat(L&F removal): remove reference to THEME events
  modules/ROOT/pages/event-handlers.adoc
Labels: Review needed :book:

#1660 Update what-is-bonita-index.adoc
  modules/ROOT/pages/what-is-bonita-index.adoc
Labels: Review needed :book:

#1664 Move process configuration overview content to index
  modules/ROOT/pages/process-configuration-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1663 Delete tutorial-overview.adoc
  modules/ROOT/pages/getting-started-index.adoc
  modules/ROOT/pages/tutorial-overview.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1670 update(Runtime + Tuning): enhance the structure
  modules/ROOT/pages/back-up-bonita-bpm-platform.adoc
  modules/ROOT/pages/runtime-index.adoc
  modules/ROOT/pages/runtime-optimization-index.adoc
  modules/ROOT/pages/runtime-tuning-index.adoc
  modules/ROOT/pages/use-gzip-compression.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1672 Update pause-and-resume-bpm-services.adoc
  modules/ROOT/pages/pause-and-resume-bpm-services.adoc
Labels: Review needed :book:

#1671 Rename bonita-bpm-installation-overview.adoc
  modules/ROOT/pages/runtime-installation-index.adoc
Labels: Review needed :book:

#1675 Create runtime-configuration-index.adoc
  modules/ROOT/pages/runtime-configuration-index.adoc
  modules/ROOT/pages/set-log-and-archive-levels.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1674 Update bonita-bpm-platform-setup.adoc
  modules/ROOT/pages/bonita-bpm-platform-setup.adoc
  modules/ROOT/pages/database-configuration.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1673 Update custom-deployment.adoc
  modules/ROOT/pages/custom-deployment.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1658 Update 2021.2 taxonomy.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1683 feat(docker): add info on docker image version
  antora.yml
  modules/ROOT/pages/bonita-docker-installation.adoc
Labels: Review done

#1686 Update(Getting Started): capitalize in title and taxo
  modules/ROOT/pages/getting-started-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:
