Repository bonitasoft/bonita-doc, pull requests merged in 2021-12, with the labels that each got.

#1851 fix(perf-tuning): add useful GC
  modules/ROOT/pages/performance-tuning.adoc
Labels: :shipit: Ready to merge :shipit:

#1855 fix(perf-tuning): change GC for Java 8
  modules/ROOT/pages/performance-tuning.adoc
Labels: Review done

#1795 feat(CORS): CORS with OIDC configuration
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done

#1860 feat(test toolkit): update test example with new toolkit syntax.
  modules/process-testing/pages/quick-start.adoc
Labels: Review needed :book:

#1853 Update release-notes.adoc
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#1854 feat(product-versioning): provide more details about the releases
  .gitattributes
  modules/ROOT/pages/product-versioning.adoc
Labels: Review done, :shipit: Ready to merge :shipit:

#1863 feat(Ubuntu): Update supported ubuntu version
  modules/runtime/pages/hardware-and-software-requirements.adoc
Labels: Review needed :book:

#1856 feat(api): Add signal API
  modules/api/pages/bpm-api.adoc
Labels: Review done

#1867 feat(Dynamic security): update doc as the feature is now SP-only
  modules/ROOT/pages/release-notes.adoc
  modules/identity/pages/bdm-access-control.adoc
  modules/identity/pages/guest-user.adoc
  modules/identity/pages/ldap-synchronizer.adoc
  modules/identity/pages/rest-api-authorization.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1848 Update multi-tenancy-and-tenant-configuration.adoc
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
Labels: Review needed :book:

#1846 Update multi-tenancy-and-tenant-configuration.adoc
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
Labels: :construction: WIP :construction:

#1868 chore(logging): document log4j2 changes
  modules/ROOT/pages/release-notes.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
  modules/runtime/pages/tomcat-bundle.adoc
  modules/setup-dev-environment/pages/logging.adoc
Labels: Review done

#1864 Add(update) SQL Server happy path
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
Labels: Review needed :book:

#1845 fix(create a connector): wrong trailing char
  modules/ROOT/pages/connector-archetype.adoc
Labels: :face_with_head_bandage: Change Needed
