Repository bonitasoft/bonita-doc, pull requests merged in 2021-02, with the labels that each got.

#1396 chore(release note): Add bugs for 7.11.5
  md/release-notes.md
Labels: Review needed :book:

#1399 fix(RN): layout changes visibility
  md/release-notes.md
Labels: Review needed :book:

#1402 update(taxonomy): remove PM and TU portal
  md/taxonomy.md
Labels: Review done

#1403 fix(taxonomy): structure for monitoring
  md/taxonomy.md
Labels: Review done

#1397 feat(connector exec): precise recovery of Connector execution
  md/connectors-execution.md
  md/execution-sequence-states-and-transactions.md
  md/queriable-logging.md
Labels: Review needed :book:

#1367 Doc(menu translation): application menu translation
  md/images/multi-language-applications/add-keys.png
  md/images/multi-language-applications/edit-localization.png
  md/images/multi-language-applications/localization.png
  md/images/multi-language-applications/menu-widget.png
  md/multi-language-applications.md
  md/taxonomy.md
Labels: Feedback integrated, Review done

#1409 doc(clusteroverview): fix passive node explanation
  md/overview-of-bonita-bpm-in-a-cluster.md
Labels: Review needed :book:

#1412 doc(hardware): update notes on mysql support for utf8mb4
  md/hardware-and-software-requirements.md
Labels: Review needed :book:

#1411 doc(7.9): inform which version supports mysql with utf8-mb4
  md/release-notes.md
Labels: Review needed :book:

#1413 feat(applications): Add how to deploy applications
  md/admin-application-overview.md
  md/applications.md
  md/user-application-overview.md
Labels: Review needed :book:

#1410 update(taxo): specify user interfaces in prod
  md/taxonomy.md
Labels: Review needed :book:

#1418 add video links - 7.9
  md/images/tv.png
  md/index.md
  md/release-notes.md
Labels: Review needed :book:

#1414 add links to videos - 7.10
  md/images/tv.png
  md/index.md
  md/release-notes.md
Labels: Review needed :book:

#1422 feat(SP upgrade): simplify upgrade doc
  md/upgrade-from-community-to-a-subscription-edition.md
Labels: Review needed :book:

#1408 doc(SSO) OIDC documentation
  md/images/oidc-overview.png
  md/single-sign-on-with-oidc.md
  md/single-sign-on-with-saml.md
  md/taxonomy.md
Labels: Feedback integrated, Review done

#1415 chore(relase): prepare release note 7.12.2
  md/release-notes.md
Labels: :construction: WIP :construction:, :fire:Merge only on release :skull_and_crossbones:
