Repository bonitasoft/bonita-doc, pull requests merged in 2021-11, with the labels that each got.

#1810 fix(custom-tomcat): typo and format
  modules/ROOT/pages/custom-deployment.adoc
Labels: Review needed :book:

#1819 fix(2021.2): apply links quick fixes
  modules/ROOT/pages/bonita-studio-download-installation.adoc
  modules/identity/pages/single-sign-on-with-oidc.adoc
  modules/process/pages/connector-archetype.adoc
  modules/security/pages/enable-cors-in-tomcat-bundle.adoc
  modules/setup-dev-environment/pages/workspaces-and-repositories.adoc
  modules/version-update/pages/migrate-from-an-earlier-version-of-bonita.adoc
Labels: Review needed :book:

#1818 Engine deep dive improvements
  modules/runtime/pages/engine-deep-dive-index.adoc
  modules/runtime/pages/how-a-bdm-is-deployed.adoc
  modules/runtime/runtime-nav.adoc
Labels: Review needed :book:

#1814 fix(custom-deploy): fix directories and clarify procedure
  modules/ROOT/pages/custom-deployment.adoc
Labels: Review needed :book:

#1821 fix: remove table for non table block
  modules/ROOT/pages/how-a-flownode-is-executed.adoc
Labels: :shipit: Ready to merge :shipit:

#1823 jattach: fix link
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1815 fix: remove extra links to unexisting commit
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/pages.adoc
Labels: Review done

#1822 Warning on tenant usage
  modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
  modules/api/pages/platform-api.adoc
  modules/identity/pages/tenant-admin-credentials.adoc
Labels: :face_with_head_bandage: Change Needed

#1756 doc(API calls): Reference all accessible APIs for a default installation
  modules/identity/identity-nav.adoc
  modules/identity/pages/admin-api-permissions.adoc
  modules/identity/pages/all-api-permissions.adoc
  modules/identity/pages/api-permissions-overview.adoc
  modules/identity/pages/rest-api-authorization.adoc
  modules/identity/pages/super-admin-api-permissions.adoc
  modules/identity/pages/user-api-permissions.adoc
Labels: Review needed :book:

#1809 feat(tests): Init test toolkit documentation
  modules/process/assets/images/images/integration-test-quick-start-process.png
  modules/process/pages/process-integration-test.adoc
  modules/process/process-nav.adoc
Labels: :construction: WIP :construction:

#1828 fix(custom-deployment): remove extra warning block
  modules/runtime/pages/custom-deployment.adoc
Labels: Review needed :book:

#1829 remove(gif): remove add-page-to-application.gif
  modules/getting-started/assets/images/images/getting-started-tutorial/create-application/add-page-to-application.gif
Labels: :shipit: Ready to merge :shipit:

#1837 Releate note for 2021.1-1116
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1836 fix(2021.2): fix unordered list in 'process:diagram-overview'
  modules/process/pages/diagram-overview.adoc
Labels: Learning

#1839 fix(release-note): 2021-1-1116
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#1826 fix(2021.2): activate the menu macro in pages where it is not activated
  modules/best-practices/pages/project-documentation-generation.adoc
  modules/getting-started/pages/configure-email-connector.adoc
  modules/getting-started/pages/create-application.adoc
  modules/getting-started/pages/create-web-user-interfaces.adoc
  modules/getting-started/pages/declare-business-variables.adoc
  modules/getting-started/pages/declare-contracts.adoc
  modules/getting-started/pages/define-business-data-model.adoc
  modules/getting-started/pages/define-who-can-do-what.adoc
  modules/getting-started/pages/draw-bpmn-diagram.adoc
  modules/identity/pages/profile-creation.adoc
Labels: Review needed :book:, Learning

#1850 doc(translation): fix method syntax change in 7.13.0: t_()
  modules/identity/pages/enforce-password-policy.adoc
Labels: Review needed :book:

#1825 Releate note for 2021.2-u1
  modules/ROOT/pages/release-notes.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:
