Repository bonitasoft/bonita-doc, pull requests merged in 2021-06, with the labels that each got.

#1532 Improve documentation structure
  modules/ROOT/assets/images/images/artifacts.png
  modules/ROOT/pages/actor-filtering.adoc
  modules/ROOT/pages/actors-index.adoc
  modules/ROOT/pages/api-index.adoc
  modules/ROOT/pages/application-creation.adoc
  modules/ROOT/pages/bonita-bpm-platform-setup.adoc
  modules/ROOT/pages/bonita-bpm-studio-hints-and-tips.adoc
  modules/ROOT/pages/bonita-bpm-studio-preferences.adoc
  modules/ROOT/pages/bonita-purpose.adoc
  modules/ROOT/pages/bonita-studio-download-installation.adoc
  modules/ROOT/pages/bonita-version-update-index.adoc
  modules/ROOT/pages/build-and-deploy-index.adoc
  modules/ROOT/pages/connectors-index.adoc
  modules/ROOT/pages/create-or-modify-a-page.adoc
  modules/ROOT/pages/customize-living-application-theme.adoc
  modules/ROOT/pages/database-connectors-index.adoc
  modules/ROOT/pages/deployment-index.adoc
  modules/ROOT/pages/development-resources-index.adoc
  modules/ROOT/pages/diagram-overview.adoc
  modules/ROOT/pages/diagrams-index.adoc
  modules/ROOT/pages/documents-index.adoc
  modules/ROOT/pages/extensions-index.adoc
  modules/ROOT/pages/getting-started-index.adoc
  modules/ROOT/pages/how-tos-index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/process-configuration-index.adoc
  modules/ROOT/pages/process-testing-index.adoc
  modules/ROOT/pages/profile-creation.adoc
  modules/ROOT/pages/project-best-practices-index.adoc
  modules/ROOT/pages/project-deploy-in-dev-suite.adoc
  modules/ROOT/pages/project-structure.adoc
  modules/ROOT/pages/runtime-administration-index.adoc
  modules/ROOT/pages/runtime-installation-index.adoc
  modules/ROOT/pages/runtime-tuning-index.adoc
  modules/ROOT/pages/setup-dev-environment-index.adoc
  modules/ROOT/pages/tenant-admin-credentials.adoc
  modules/ROOT/pages/troubleshooting.adoc
  modules/ROOT/pages/tutorial-overview.adoc
  modules/ROOT/pages/web-service-connector-overview.adoc
  modules/ROOT/pages/what-is-bonita-index.adoc
  modules/ROOT/taxonomy.adoc
  old_taxonomy.adoc
Labels: :construction: WIP :construction:

#1594 The installBDM method is deprecated in 2021.2
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1591 fix(links): fix bad links to anchors
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/runtime-monitoring.adoc
  modules/ROOT/pages/ui-designer-overview.adoc
  modules/ROOT/pages/variables.adoc
  modules/ROOT/pages/widgets.adoc
Labels: Review needed :book:

#1592 doc(contrib): provided a basic contribution Readme.adoc
  CONTRIBUTING.md
  README.adoc
  README.md
Labels: Review needed :book:

#1582 fix(migrate): replace CP with CSC for 7.11+
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
Labels: Review needed :book:

#1581 fix(CP_by_CSC): replace Customer Portal by Customer Service Center
  modules/ROOT/pages/bonita-as-windows-service.adoc
  modules/ROOT/pages/bonita-bpm-studio-installation.adoc
  modules/ROOT/pages/custom-deployment.adoc
  modules/ROOT/pages/licenses.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/set-up-continuous-integration.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/tomcat-bundle.adoc
  modules/ROOT/pages/ubuntu-openjdk-tomcat-postgresql.adoc
Labels: Review needed :book:

#1569 fix(bdm) Eager vs Lazy warning
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
Labels: Review done

#1573 update(LDAP authentication): Add troubleshooting tips
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
Labels: Review needed :book:

#1598 feat(bdm): document how to access bdm jars via a sample code
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
Labels: Review needed :book:

#1599 rn(C4R): document the pages / rest API examples removal
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1601 fix(bdm_limitations): change type attribute not supported
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
Labels: Review needed :book:

#1543 fix(database-conf): detail BDM grants oracle
  modules/ROOT/pages/database-configuration.adoc
Labels: Review needed :book:

#1595 update(ldap sync): add search parameters info
  modules/ROOT/pages/ldap-synchronizer.adoc
Labels: Review needed :book:

#1596 fix(ldap sync): mandatory parameter enforce_ssl true
  modules/ROOT/pages/ldap-synchronizer.adoc
Labels: Review needed :book:

#1603 update(taxonomy): remove first engine API part
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:
