Repository bonitasoft/bonita-doc, pull requests merged in 2021-10, with the labels that each got.

#1748 feat(docker): Explain how to configure a postgres container for bonita
  modules/ROOT/pages/bonita-docker-installation.adoc
Labels: Review done, :face_with_head_bandage: Change Needed

#1680 Update(install-cluster): rename FAQ to Troubleshooting
  modules/ROOT/pages/install-a-bonita-bpm-cluster.adoc
Labels: Review done, Learning

#1681 fix(performance-troubleshooting): improve connectors
  modules/ROOT/pages/performance-troubleshooting.adoc
Labels: Review needed :book:, Feedback integrated, Learning

#1747 chore: skip preview for PR created from fork repositories
  .github/workflows/build-pr-preview.yml
Labels: Review needed :book:

#1752 doc(reporting): Delete pages about reporting for now
  modules/ROOT/pages/create-a-report.adoc
  modules/ROOT/pages/portal-removal.adoc
  modules/ROOT/pages/reporting-overview.adoc
Labels: Review needed :book:
