Repository bonitasoft/bonita-doc, pull requests merged in 2021-04, with the labels that each got.

#1491 fix(2021.1): fix remaining asciidoc warnings
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
Labels: Review needed :book:

#1515 fix(format): fix various asciidoc syntax errors
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
Labels: Review done

#1501 fix(2021.2): do not mention release dates
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1520 fix(SAML) fix formatting
  modules/ROOT/pages/single-sign-on-with-saml.adoc
Labels: :face_with_head_bandage: Change Needed

#1516 fix(format): fix wrong italic+bold asciidoc conversion
  modules/ROOT/pages/about.adoc
  modules/ROOT/pages/analytics.adoc
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/bonita-bpm-studio-hints-and-tips.adoc
  modules/ROOT/pages/bonita-bpm-studio-installation.adoc
  modules/ROOT/pages/cases.adoc
  modules/ROOT/pages/cmis.adoc
  modules/ROOT/pages/custom-profiles.adoc
  modules/ROOT/pages/custom-user-information-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/custom-user-information-in-bonita-bpm-studio.adoc
  modules/ROOT/pages/database-configuration.adoc
  modules/ROOT/pages/database-connector-configuration.adoc
  modules/ROOT/pages/deactivate-a-user.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/environments.adoc
  modules/ROOT/pages/group.adoc
  modules/ROOT/pages/import-export-an-organization.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/live-update.adoc
  modules/ROOT/pages/log-in-and-log-out.adoc
  modules/ROOT/pages/manage-a-user.adoc
  modules/ROOT/pages/operations.adoc
  modules/ROOT/pages/process-manager.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/role.adoc
  modules/ROOT/pages/sap-jco-3.adoc
  modules/ROOT/pages/script.adoc
  modules/ROOT/pages/tasks.adoc
  modules/ROOT/pages/ubuntu-openjdk-tomcat-postgresql.adoc
  modules/ROOT/pages/web-service-connector-overview.adoc
  modules/ROOT/pages/web-service-tutorial.adoc
  modules/ROOT/pages/widgets.adoc
Labels: Review needed :book:

#1527 fix(monitoring): various minor fixes and improvements
  modules/ROOT/pages/runtime-monitoring.adoc
Labels: Review needed :book:

#1522 update(release note): add bug fixes for 7.12.3 version
  modules/ROOT/pages/release-notes.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:

#1536 update(archives): v5 contact support to zip
  modules/ROOT/pages/archives.adoc
Labels: Review needed :book:

#1504 update(index): add card desc
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1505 update(index): add card description
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1526 fix(product-versioning): format xml example
  modules/ROOT/pages/product-versioning.adoc
Labels: Review needed :book:

#1508 update(index): add cards description
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1506 fix(index): put the right 7.7 content and add desc
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1507 update(index): add cards description
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#1513 feat: add more info on calling apis inside event handler
  modules/ROOT/pages/event-handlers.adoc
Labels: Review needed :book:

#1544 feat(purge_tool): Add purge tool changelog
  modules/ROOT/pages/purge-tool-changelog.adoc
  modules/ROOT/taxonomy.adoc
Labels: :face_with_head_bandage: Change Needed
