Repository bonitasoft/bonita-doc, pull requests merged in 2021-09, with the labels that each got.

#1687 feat(Custom profile): explain convertion to App in RN
  modules/ROOT/assets/images/images/temp-release-notes-specific/custom_profile.png
  modules/ROOT/assets/images/images/temp-release-notes-specific/new_app_converted_from_custom_profile.png
  modules/ROOT/assets/images/images/temp-release-notes-specific/new_app_directory_with_converted_custom_profile.png
  modules/ROOT/assets/images/images/temp-release-notes-specific/old_profile_navigation.png
  modules/ROOT/pages/release-notes.adoc
Labels: Feedback integrated

#1694 feat(Java 11): update doc to point to Java 11-only support
  modules/ROOT/pages/customize-living-application-theme.adoc
  modules/ROOT/pages/groovy-in-bonita.adoc
  modules/ROOT/pages/hardware-and-software-requirements.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
Labels: Review needed :book:

#1662 feat(dev): custom library development example
  modules/ROOT/pages/custom-library-development.adoc
  modules/ROOT/pages/define-who-can-do-what.adoc
  modules/ROOT/taxonomy.adoc
Labels: :construction: WIP :construction:

#1692 feat(Portal): Remove mention of Portal from documentation part 1
  modules/ROOT/assets/images/images/UI2021.1/admin_applications.png
  modules/ROOT/assets/images/images/UI2021.1/bdm-management.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/applications-icon.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/portal-icon.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/web-browser-display-application-list.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/web-browser-display-portal.png
  modules/ROOT/pages/about.adoc
  modules/ROOT/pages/access-control-api.adoc
  modules/ROOT/pages/actors.adoc
  modules/ROOT/pages/admin-application-groups-list.adoc
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/api-glossary.adoc
  modules/ROOT/pages/application-creation.adoc
  modules/ROOT/pages/applications.adoc
  modules/ROOT/pages/approaches-to-managing-organizations-and-actor-mapping.adoc
  modules/ROOT/pages/bdm-access-control.adoc
  modules/ROOT/pages/bdm-management-in-bonita-applications.adoc
  modules/ROOT/pages/bonita-applications-interface-overview.adoc
  modules/ROOT/pages/bonita-as-windows-service.adoc
  modules/ROOT/pages/bonita-bpm-applications-urls.adoc
  modules/ROOT/pages/bonita-bpm-portal-interface-overview.adoc
  modules/ROOT/pages/bonita-bpm-studio-preferences.adoc
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/bonita-purpose.adoc
  modules/ROOT/pages/bonita-studio-download-installation.adoc
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/build-a-process-for-deployment.adoc
  modules/ROOT/pages/cache-configuration-and-policy.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/configure-a-test-organization.adoc
  modules/ROOT/pages/custom-user-information-in-bonita-applications.adoc
  modules/ROOT/pages/custom-user-information-in-bonita-bpm-studio.adoc
  modules/ROOT/pages/diagram-tasks.adoc
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
  modules/ROOT/pages/log-in-and-log-out.adoc
  modules/ROOT/pages/mobile-portal.adoc
  modules/ROOT/pages/organization-in-bonita-applications-overview.adoc
  modules/ROOT/pages/organization-overview.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/profile-list-portal.adoc
  modules/ROOT/pages/profiles-applications-overview.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1700 feat(docker): explain 'jattach' inside docker image
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:, Feedback integrated

#1697 feat(Portal): Remove mention of Portal from documentation part 3
  modules/ROOT/assets/images/images/videos-6_0/import_an_organization_into_bonita_applications.mp4
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/bonita-version-update-index.adoc
  modules/ROOT/pages/hardware-and-software-requirements.adoc
  modules/ROOT/pages/how-a-flownode-is-executed.adoc
  modules/ROOT/pages/identity-api.adoc
  modules/ROOT/pages/import-and-export-a-process.adoc
  modules/ROOT/pages/import-export-an-organization.adoc
  modules/ROOT/pages/key-concepts.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/layout-development.adoc
  modules/ROOT/pages/layouts.adoc
  modules/ROOT/pages/ldap-synchronizer.adoc
  modules/ROOT/pages/licenses.adoc
  modules/ROOT/pages/live-update.adoc
  modules/ROOT/pages/log-in-and-log-out.adoc
  modules/ROOT/pages/log-in-with-cas.adoc
  modules/ROOT/pages/logging.adoc
  modules/ROOT/pages/maintenance-operation.adoc
  modules/ROOT/pages/manage-users.adoc
  modules/ROOT/pages/migrate-a-form-from-6-x.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita.adoc
  modules/ROOT/pages/migration-overview.adoc
  modules/ROOT/pages/migration-tool.adoc
  modules/ROOT/pages/monitoring.adoc
  modules/ROOT/pages/multi-language-pages.adoc
  modules/ROOT/pages/overview-of-bonita-bpm-in-a-cluster.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1710 feat(RN): Add 7.12.8 release note
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1704 doc(applications): Add information about the new applications
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1696 fix(migration): fix reference to other version RN page
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
Labels: Review needed :book:

#1716 feat(portal): Remove portal mentions from pages
  modules/ROOT/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/ROOT/pages/embed-engine.adoc
Labels: Review needed :book:

#1717 feat(portal): Remove portal mentions from purge-tool page
  modules/ROOT/pages/purge-tool-deletion-volume-testing.adoc
Labels: Review needed :book:

#1723 Create xref:application-directory-application.adoc
  modules/ROOT/assets/images/images/edit-error-page-image.png
  modules/ROOT/pages/application-directory.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review done

#1707 feat(Portal): Remove mention of Portal from documentation part 4
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/bdm-access-control.adoc
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/bonita-platform-setup.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/configurable-archive.adoc
  modules/ROOT/pages/csrf-security.adoc
  modules/ROOT/pages/custom-deployment.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/embed-engine.adoc
  modules/ROOT/pages/enforce-password-policy.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/event-handlers.adoc
  modules/ROOT/pages/first-steps-after-setup.adoc
  modules/ROOT/pages/install-a-bonita-bpm-cluster.adoc
  modules/ROOT/pages/licenses.adoc
  modules/ROOT/pages/manage-the-platform.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita.adoc
  modules/ROOT/pages/navigation.adoc
  modules/ROOT/pages/optimize-user-tasklist.adoc
  modules/ROOT/pages/organization-in-bonita-applications-overview.adoc
  modules/ROOT/pages/organization-management-in-bonita-bpm-studio.adoc
  modules/ROOT/pages/organization-overview.adoc
  modules/ROOT/pages/overview-of-bonita-bpm-in-a-cluster.adoc
  modules/ROOT/pages/pages-development.adoc
  modules/ROOT/pages/pages.adoc
  modules/ROOT/pages/parameters.adoc
  modules/ROOT/pages/performance-troubleshooting.adoc
  modules/ROOT/pages/performance-tuning.adoc
  modules/ROOT/pages/pools-and-lanes.adoc
  modules/ROOT/pages/portal-api.adoc
  modules/ROOT/pages/process-testing-overview.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/profile-creation.adoc
  modules/ROOT/pages/profiles-applications-overview.adoc
  modules/ROOT/pages/project-deploy-in-dev-suite.adoc
  modules/ROOT/pages/queriable-logging.adoc
  modules/ROOT/pages/react-page-dependencies.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/ROOT/pages/resource-management.adoc
  modules/ROOT/pages/rest-api-authentication.adoc
  modules/ROOT/pages/rest-api-authorization.adoc
  modules/ROOT/pages/rest-api-extension-archetype.adoc
  modules/ROOT/pages/rest-api-extensions.adoc
  modules/ROOT/pages/rest-api-overview.adoc
  modules/ROOT/pages/run-a-process-from-bonita-bpm-studio-for-testing.adoc
  modules/ROOT/pages/runtime-configuration-index.adoc
  modules/ROOT/pages/set-log-and-archive-levels.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/tomcat-bundle.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
  modules/ROOT/pages/using-list-and-search-methods.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1714 feat(Portal): Remove mention of Portal from documentation part 5
  modules/ROOT/pages/set-log-and-archive-levels.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/single-sign-on-with-kerberos.adoc
  modules/ROOT/pages/single-sign-on-with-oidc.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/ssl.adoc
  modules/ROOT/pages/theme-development.adoc
  modules/ROOT/pages/themes.adoc
  modules/ROOT/pages/ui-designer-overview.adoc
  modules/ROOT/pages/uid-case-overview-tutorial.adoc
  modules/ROOT/pages/use-bonita-acm.adoc
  modules/ROOT/pages/user-application-case-list.adoc
  modules/ROOT/pages/user-application-overview.adoc
  modules/ROOT/pages/user-authentication-overview.adoc
  modules/ROOT/pages/user-process-list.adoc
  modules/ROOT/pages/user-task-list.adoc
  modules/ROOT/pages/web-service-connector-overview.adoc
  modules/ROOT/pages/web-service-tutorial.adoc
Labels: Review needed :book:

#1725 Update custom-applications-index.adoc
  modules/ROOT/pages/custom-applications-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:, Feedback integrated

#1722 doc(Portal removal): Add page for portal removal
  modules/ROOT/pages/analytics.adoc
  modules/ROOT/pages/applications.adoc
  modules/ROOT/pages/approaches-to-managing-organizations-and-actor-mapping.adoc
  modules/ROOT/pages/bonita-bpm-overview.adoc
  modules/ROOT/pages/bonita-purpose.adoc
  modules/ROOT/pages/build-a-process-for-deployment.adoc
  modules/ROOT/pages/cases.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/create-a-report.adoc
  modules/ROOT/pages/creating-a-new-look-feel.adoc
  modules/ROOT/pages/fault-tolerance.adoc
  modules/ROOT/pages/first-steps-after-setup.adoc
  modules/ROOT/pages/group.adoc
  modules/ROOT/pages/living-application-layout.adoc
  modules/ROOT/pages/manage-a-user.adoc
  modules/ROOT/pages/managing-look-feel.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita.adoc
  modules/ROOT/pages/mobile-portal.adoc
  modules/ROOT/pages/parameters.adoc
  modules/ROOT/pages/portal-removal.adoc
  modules/ROOT/pages/portal-user-case-list.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/profile-list-portal.adoc
  modules/ROOT/pages/profiles-applications-overview.adoc
  modules/ROOT/pages/restore-default-look-feel.adoc
  modules/ROOT/pages/role.adoc
  modules/ROOT/pages/run-a-process-from-bonita-bpm-studio-for-testing.adoc
  modules/ROOT/pages/tasks.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1703 Update taxonomy.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:, Feedback integrated

#1733 Add admin app
  modules/ROOT/pages/admin-application-overview.adoc
  modules/ROOT/pages/administrator-application-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review done, Feedback integrated

#1701 Create content for runtime-installation-index.adoc
  modules/ROOT/pages/runtime-installation-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:

#1665 Move process testing overview content to the index
  modules/ROOT/pages/process-testing-index.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review needed :book:, Feedback integrated

#1732 doc(Portal removal): Update Portal images to new Living App images
  modules/ROOT/assets/images/images/UI2021.1/admin-application-groups-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-application-process-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-application-profiles-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-application-resources-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-application-task-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-application-users-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-case-list.png
  modules/ROOT/assets/images/images/UI2021.1/admin-process-list-portal.png
  modules/ROOT/assets/images/images/UI2021.1/admin-task-list-portal.png
  modules/ROOT/assets/images/images/UI2021.1/admin_applications.png
  modules/ROOT/assets/images/images/UI2021.1/admin_resources_portal.png
  modules/ROOT/assets/images/images/UI2021.1/analytics.png
  modules/ROOT/assets/images/images/UI2021.1/bdm-management.png
  modules/ROOT/assets/images/images/UI2021.1/custom-user-info.png
  modules/ROOT/assets/images/images/UI2021.1/groups-portal.png
  modules/ROOT/assets/images/images/UI2021.1/install-export.png
  modules/ROOT/assets/images/images/UI2021.1/logout.png
  modules/ROOT/assets/images/images/UI2021.1/monitoring.png
  modules/ROOT/assets/images/images/UI2021.1/navigation-application.png
  modules/ROOT/assets/images/images/UI2021.1/navigation-portal.png
  modules/ROOT/assets/images/images/UI2021.1/profiles-portal.png
  modules/ROOT/assets/images/images/UI2021.1/roles-portal.png
  modules/ROOT/assets/images/images/UI2021.1/select-language.png
  modules/ROOT/assets/images/images/UI2021.1/sign-out.png
  modules/ROOT/assets/images/images/UI2021.1/user-case-details.png
  modules/ROOT/assets/images/images/UI2021.1/user-case-list-app.png
  modules/ROOT/assets/images/images/UI2021.1/user-case-list.png
  modules/ROOT/assets/images/images/UI2021.1/user-case-sort-App.png
  modules/ROOT/assets/images/images/UI2021.1/user-case-sort-Portal.png
  modules/ROOT/assets/images/images/UI2021.1/user-deactivate.png
  modules/ROOT/assets/images/images/UI2021.1/user_process_list.png
  modules/ROOT/assets/images/images/UI2021.1/users-portal.png
  modules/ROOT/assets/images/images/applicationDescriptors/applicationDescriptorEditor_v2.png
  modules/ROOT/assets/images/images/applicationDescriptors/applicationDescriptorEditor_v3.png
  modules/ROOT/assets/images/images/applicationDescriptors/emptyApplicationFile_v2.png
  modules/ROOT/assets/images/images/applicationDescriptors/emptyApplicationFile_v3.png
  modules/ROOT/assets/images/images/display_task_name_and_description.png
  modules/ROOT/assets/images/images/getting-started-tutorial/create-application/applications-icon.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/applications-icon.png
  modules/ROOT/assets/images/images/getting-started-tutorial/installation/web-browser-display-application-list.png
  modules/ROOT/assets/images/images/images-6_0/admin_view7.1.png
  modules/ROOT/assets/images/images/images-6_0/connector_failed.png
  modules/ROOT/assets/images/images/images-6_0/living_app_navigation.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_0.login.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_1b.tasksapps.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_2.available.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_3.todo.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_4.tasks.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_6.addsubtask2.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_7.step1_comments.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_8.step1_details.png
  modules/ROOT/assets/images/images/images-6_0/mobile7.x_9.step1_subtasks.png
  modules/ROOT/assets/images/images/images-6_0/user_view7.x.png
  modules/ROOT/assets/images/images/tasklist-elements.png
  modules/ROOT/assets/images/images/tasklist-fullpage.png
  modules/ROOT/assets/images/images/tasklist-popup.png
  modules/ROOT/assets/images/images/tasklist-settings-and-tabs.png
  modules/ROOT/assets/images/images/user_tasklist.png
  modules/ROOT/pages/admin-application-process-list.adoc
  modules/ROOT/pages/application-creation.adoc
Labels: Review needed :book:

#1735 fix(applications): App creation link in apps indexes
  modules/ROOT/pages/administrator-application-index.adoc
  modules/ROOT/pages/super-administrator-application-index.adoc
  modules/ROOT/pages/user-application-index.adoc
Labels: Review needed :book:

#1736 Create process-management-index.adoc
  modules/ROOT/pages/process-management-index.adoc
Labels: Review done, Feedback integrated

#1691 doc(BDM in cluster): specify the BDM in cluster
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
Labels: Review needed :book:

#1690 RN(runtime improvement): 4xx error handling
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1741 feat(Look and feel): Re-write look and feel reference
  modules/ROOT/pages/creating-a-new-look-feel.adoc
  modules/ROOT/pages/portal-removal.adoc
  modules/ROOT/pages/restore-default-look-feel.adoc
Labels: Review done

#1737 doc(Pages): Update remaining pages to remove reference to Portal
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/logging.adoc
  modules/ROOT/pages/multi-language-pages.adoc
  modules/ROOT/pages/pages-development.adoc
  modules/ROOT/pages/portal-api.adoc
  modules/ROOT/pages/profile-creation.adoc
  modules/ROOT/pages/profiles-applications-overview.adoc
  modules/ROOT/pages/reverse-proxy-configuration.adoc
  modules/ROOT/pages/run-a-process-from-bonita-bpm-studio-for-testing.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/single-sign-on-with-oidc.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/tenant-admin-credentials.adoc
Labels: Review needed :book:

#1745 update(studio-projects): Add warning for .bos import
  modules/ROOT/pages/workspaces-and-repositories.adoc
Labels: Review needed :book:
