Repository bonitasoft/bonita-doc, pull requests merged in 2022-11, with the labels that each got.

#2201 fix: remove hardcoded links to BCD, Cloud and Bonita docs
  .github/workflows/build-pr-preview.yml
  modules/ROOT/pages/creating-a-new-look-feel.adoc
  modules/ROOT/pages/portal-removal.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/best-practices/pages/design-methodology.adoc
  modules/bonita-overview/bonita-overview-nav.adoc
  modules/bonita-overview/pages/bonita-bpm-overview.adoc
  modules/bonita-overview/pages/what-is-bonita-index.adoc
  modules/getting-started/pages/create-application.adoc
  modules/pages-and-forms/pages/create-or-modify-a-page.adoc
  modules/process/pages/ldap.adoc
Labels: :heavy_check_mark: Question Answered

#2215 ci: make the "Vale action" use the latest release
  .github/workflows/contribution-check.yml
Labels: Review done

#2216 ci: reduce runs of the 'contribution-check' workflow
  .github/workflows/contribution-check.yml
Labels: Review needed :book:

#2218 ci: disable vale-action
  .github/workflows/contribution-check.yml
Labels: Review needed :book:

#2213 feat(tenancy removal): remove Tenant rest apis
  modules/api/pages/platform-api.adoc
  modules/api/pages/portal-api.adoc
  modules/api/pages/system-api.adoc
Labels: Review done

#2217 ci: update GitHub Actions with dependabot
  .github/dependabot.yml
Labels: Review needed :book:

#2214 refactor(style): remove extra comments
  modules/ROOT/pages/admin-application-groups-list.adoc
  modules/ROOT/pages/admin-application-process-list.adoc
  modules/ROOT/pages/admin-application-profiles-list.adoc
  modules/ROOT/pages/admin-application-resources-list.adoc
  modules/ROOT/pages/admin-application-roles-list.adoc
  modules/ROOT/pages/admin-application-task-list.adoc
  modules/ROOT/pages/admin-application-users-list.adoc
  modules/ROOT/pages/analytics.adoc
  modules/ROOT/pages/applications.adoc
  modules/ROOT/pages/bdm-management-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/bo-multiple-refs-tutorial.adoc
  modules/ROOT/pages/cases.adoc
  modules/ROOT/pages/configure-email-connector.adoc
  modules/ROOT/pages/create-web-user-interfaces.adoc
  modules/ROOT/pages/custom-user-information-in-bonita-bpm-portal.adoc
  modules/ROOT/pages/deactivate-a-user.adoc
  modules/ROOT/pages/declare-business-variables.adoc
  modules/ROOT/pages/declare-contracts.adoc
  modules/ROOT/pages/define-who-can-do-what.adoc
  modules/ROOT/pages/design-application-page.adoc
  modules/ROOT/pages/diagram-tasks.adoc
  modules/ROOT/pages/draw-bpmn-diagram.adoc
  modules/ROOT/pages/group.adoc
  modules/ROOT/pages/import-export-an-organization.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/log-in-and-log-out.adoc
  modules/ROOT/pages/manage-jar-files.adoc
  modules/ROOT/pages/navigation.adoc
  modules/ROOT/pages/optimize-user-tasklist.adoc
  modules/ROOT/pages/portal-user-case-list.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/profile-list-portal.adoc
  modules/ROOT/pages/repeat-a-container-for-a-collection-of-data.adoc
  modules/ROOT/pages/resource-management.adoc
  modules/ROOT/pages/role.adoc
  modules/ROOT/pages/rta-mail-template.adoc
  modules/ROOT/pages/tasks.adoc
  modules/ROOT/pages/ui-designer-overview.adoc
  modules/ROOT/pages/uid-vertical-tabs-container-tutorial.adoc
  modules/ROOT/pages/user-application-case-list.adoc
  modules/ROOT/pages/user-process-list.adoc
  modules/ROOT/pages/user-task-list.adoc
Labels: Review needed :book:

#2221 docs(RN): Update release note 2022.2
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2227 docs(UID troubleshooting): add new troubleshooting section for case sensitivity issue
  modules/bonita-overview/pages/ui-designer-overview.adoc
Labels: Review needed :book:

#2231 docs(2021.2): Update release note for 7.13.7
  .github/styles/Vocab/Base/accept.txt
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2244 docs(Product versions): Add versions for 7.13.7
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2243 docs(2021.1): Update release note for 7.12.13
  modules/ROOT/pages/product-versioning.adoc
  modules/ROOT/pages/release-notes.adoc
Labels: :shipit: Ready to merge :shipit:, :cry: Rebase needed :cry:, :fire:Merge only on release :skull_and_crossbones:
