Repository bonitasoft/bonita-doc, pull requests merged in 2022-04, with the labels that each got.

#1977 feat(http api): update doc with new easy way to (de)activate
  modules/api/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/identity/pages/ldap-synchronizer.adoc
  modules/identity/pages/rest-api-authorization.adoc
  modules/identity/pages/single-sign-on-with-kerberos.adoc
Labels: :heavy_check_mark: Question Answered

#1982 doc(UpdateTool): New page for Update tool
  modules/ROOT/assets/images/images/images-6_0/update_bigsteps.png
  modules/ROOT/pages/bonita-docker-installation.adoc
  modules/ROOT/pages/maintenance-operation.adoc
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/migration-overview.adoc
  modules/ROOT/pages/overview-of-bonita-bpm-in-a-cluster.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/ROOT/pages/runtime-installation-index.adoc
  modules/ROOT/taxonomy.adoc
  modules/version-update/pages/update-overview.adoc
  modules/version-update/pages/update-tools-changelog.adoc
  modules/version-update/pages/update-with-migration-tool.adoc
  modules/version-update/pages/update-with-update-tool.adoc
  modules/version-update/version-update-nav.adoc
Labels: Review needed :book:

#2028 Update (runtime-installation): fix structure
  modules/runtime/pages/runtime-installation-index.adoc
  modules/runtime/runtime-nav.adoc
Labels: Review needed :book:

#2024 feat(REST API authorizations): several improvements
  modules/identity/pages/rest-api-authorization.adoc
Labels: Review needed :book:

#2025 doc(archives): create a dedicated paragraph for Bonita
  modules/ROOT/pages/archives.adoc
Labels: Review done, :shipit: Ready to merge :shipit:

#2032 fix(renaming): add aliases on renamed pages
  modules/version-update/pages/update-overview.adoc
Labels: Review done, :shipit: Ready to merge :shipit:

#2033 fix(2021.2): remove extra migration page
  modules/ROOT/pages/release-notes.adoc
  modules/runtime/pages/runtime-index.adoc
  modules/version-update/pages/bonita-version-update-index.adoc
  modules/version-update/pages/migrate-from-an-earlier-version-of-bonita.adoc
  modules/version-update/pages/update-overview.adoc
Labels: Review needed :book:

#2031 feat(versions): add the last 2 missing versions
  modules/ROOT/pages/product-versioning.adoc
Labels: :shipit: Ready to merge :shipit:

#2046 update(release notes): add info on bug fixes
  modules/ROOT/pages/release-notes.adoc
Labels: :shipit: Ready to merge :shipit:

#2045 update(release-notes): add bugfixes of 2021.1
  modules/ROOT/pages/release-notes.adoc
Labels: :shipit: Ready to merge :shipit:

#2034 update(product versioning): element and table
  modules/version-update/pages/product-versioning.adoc
Labels: :shipit: Ready to merge :shipit:

#2000 docs(Update Tool): Update Bonita Runtime pages
  modules/ROOT/pages/migrate-from-an-earlier-version-of-bonita-bpm.adoc
  modules/ROOT/pages/migration-overview.adoc
  modules/ROOT/pages/update-overview.adoc
Labels: Review needed :book:

#2037 feat(product-versioning): replace `artifact` by `element`
  modules/version-update/pages/product-versioning.adoc
Labels: :shipit: Ready to merge :shipit:

#2035 fix(7.11): fix Asciidoctor warnings
  modules/ROOT/pages/define-business-data-model.adoc
  modules/version-update/pages/update-with-update-tool.adoc
Labels: Review needed :book:

#2036 fix(docker pages): move, rename, edit content
  modules/runtime/pages/docker-deep-dive.adoc
  modules/runtime/pages/docker-index.adoc
  modules/runtime/runtime-nav.adoc
Labels: Review done

#2042 fix(cust-auth): use java 11 and specific bonita version in example
  modules/identity/pages/custom-authorization-rule-mapping.adoc
Labels: Review needed :book:
