Repository bonitasoft/bonita-doc, pull requests merged in 2022-10, with the labels that each got.

#2129 docs(2022.2): update product versioning information
  modules/version-update/pages/product-versioning.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:, :warning: Do not merge :warning:

#2179 feat(archives): keep a single paragraph for 7.6 and 7.7
  README.md
  modules/ROOT/pages/archives.adoc
Labels: Review needed :book:

#2180 docs(RN): adding bug fixes
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2178 docs(troubleshooting): refactor some troubleshooting section
  modules/ROOT/pages/bonita-bpm-platform-setup.adoc
  modules/ROOT/pages/bonita-bpm-studio-preferences.adoc
  modules/ROOT/pages/generate-pdf-from-an-office-document.adoc
Labels: Review done

#2185 ci: add write permissions for the check PR title workflow
  .github/workflows/contribution-check.yml
Labels: Review needed :book:

#2184 ci: add write permissions for the stale workflow
  .github/workflows/close-stale.yml
Labels: Review needed :book:

#2193 fix(alias): add alias for migration-tool page in update-tools-changelog
  modules/version-update/pages/update-tools-changelog.adoc
Labels: :shipit: Ready to merge :shipit:

#2194 fix(alias): add alias for migration-tool page in update-tools-changelog
  modules/version-update/pages/update-tools-changelog.adoc
Labels: :shipit: Ready to merge :shipit:

#2189 fix(2021.1): remove hard coded links to the production documentation site
  .github/workflows/build-pr-preview.yml
  antora.yml
  modules/ROOT/pages/admin-application-overview.adoc
  modules/ROOT/pages/automating-builds.adoc
  modules/ROOT/pages/bonita-studio-download-installation.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/create-application.adoc
  modules/ROOT/pages/creating-an-actor-filter.adoc
  modules/ROOT/pages/how-a-bdm-is-deployed.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/ldap.adoc
  modules/ROOT/pages/set-up-continuous-integration.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/user-application-overview.adoc
Labels: :shipit: Ready to merge :shipit:, Feedback integrated

#2196 fix(typos): Fix typos thanks to the Vale tool
  modules/ROOT/pages/activities-tasks-flow-nodes-api.adoc
  modules/ROOT/pages/actors-process-connectors-api.adoc
  modules/ROOT/pages/admin-application-overview.adoc
  modules/ROOT/pages/admin-application-process-list.adoc
  modules/ROOT/pages/admin-application-resources-list.adoc
  modules/ROOT/pages/automating-builds.adoc
  modules/ROOT/pages/bdm-access-control.adoc
  modules/ROOT/pages/bo-multiple-refs-tutorial.adoc
  modules/ROOT/pages/bonita-bpm-overview.adoc
  modules/ROOT/pages/bonita-bpm-studio-installation.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/ROOT/pages/csrf-security.adoc
  modules/ROOT/pages/data-documents-api.adoc
  modules/ROOT/pages/datetimes-management-tutorial.adoc
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
  modules/ROOT/pages/design-methodology.adoc
  modules/ROOT/pages/diagram-tasks.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/execution-sequence-states-and-transactions.adoc
  modules/ROOT/pages/fault-tolerance.adoc
  modules/ROOT/pages/gateways.adoc
  modules/ROOT/pages/handling-documents.adoc
  modules/ROOT/pages/install-a-bonita-bpm-cluster.adoc
  modules/ROOT/pages/key-concepts.adoc
  modules/ROOT/pages/languages.adoc
  modules/ROOT/pages/layout-development.adoc
  modules/ROOT/pages/ldap-synchronizer.adoc
  modules/ROOT/pages/list-of-documents.adoc
  modules/ROOT/pages/manage-control-in-forms.adoc
  modules/ROOT/pages/migrate-a-form-from-6-x.adoc
  modules/ROOT/pages/naming-conventions.adoc
  modules/ROOT/pages/operations.adoc
  modules/ROOT/pages/organization-management-in-bonita-bpm-studio.adoc
  modules/ROOT/pages/pages.adoc
  modules/ROOT/pages/performance-tuning.adoc
  modules/ROOT/pages/processes.adoc
  modules/ROOT/pages/repeat-a-container-for-a-collection-of-data.adoc
  modules/ROOT/pages/rest-api-authentication.adoc
  modules/ROOT/pages/rest-api-authorization.adoc
  modules/ROOT/pages/salesforce.adoc
  modules/ROOT/pages/set-log-and-archive-levels.adoc
  modules/ROOT/pages/set-up-continuous-integration.adoc
  modules/ROOT/pages/share-a-repository-on-github.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/single-sign-on-with-kerberos.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/specify-data-in-a-process-definition.adoc
  modules/ROOT/pages/tutorial-overview.adoc
  modules/ROOT/pages/ui-designer-overview.adoc
  modules/ROOT/pages/user-application-overview.adoc
  modules/ROOT/pages/web-service-tutorial.adoc
  modules/ROOT/pages/widget-properties.adoc
  modules/ROOT/pages/work-execution.adoc
  modules/ROOT/pages/workspaces-and-repositories.adoc
Labels: :shipit: Ready to merge :shipit:

#2197 chore(deps): merge Web to Engine deps report
  modules/ROOT/pages/bonita-runtime-dependencies.adoc
  modules/ROOT/pages/bonita-web-dependencies.adoc
  modules/ROOT/pages/dependencies-index.adoc
Labels: Review needed :book:

#2199 fix(deps): fix incorrect page aliases definition
  modules/ROOT/pages/bonita-runtime-dependencies.adoc
Labels: :shipit: Ready to merge :shipit:

#2202 fix(REST API): fix broken link to process instantiation
  modules/api/pages/cases-process-instance-api.adoc
Labels: :shipit: Ready to merge :shipit:

#2200 fix: use correct syntax for links to the BCD docs
  .github/workflows/build-pr-preview.yml
  modules/ROOT/pages/admin-application-overview.adoc
  modules/ROOT/pages/automating-builds.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/set-up-continuous-integration.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/user-application-overview.adoc
  modules/ROOT/pages/what-is-bonita.adoc
Labels: Review needed :book:

#2209 docs(OIDC): clarify principal-attribute usage
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done, Review needed :book:

#2210 feat(OIDC): principal-attribute new supported values
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done
