Repository bonitasoft/bonita-doc, pull requests merged in 2022-09, with the labels that each got.

#2115 Fix(RN): reapply 2022.1 u2 change once released
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: Review done, 2022.1-u2 (7.14.2)

#2136 fix(case api): Add title to page so that it's not untitled
  modules/api/pages/cases-process-instance-api.adoc
Labels: :shipit: Ready to merge :shipit:

#2134 chore: separate build and preview worflow
  .github/workflows/build-pr-preview.yml
  .github/workflows/publish-pr-preview.yml
Labels: Review needed :book:

#2128 feat(RN): use 2022.1-u2 changes for 2022.1-u3
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: Review done, Review needed :book:

#2147 feat(RN): 2021.1 (7.12.12)
  modules/ROOT/pages/product-versioning.adoc
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2148 feat(update-tool): Add update tool 3.0.2 release note.
  modules/version-update/pages/update-tools-changelog.adoc
Labels: Review needed :book:
