Repository bonitasoft/bonita-doc, pull requests merged in 2022-02, with the labels that each got.

#1909 chore(7.10): mark as 'out of support'
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-pr-preview.yml
  .github/workflows/close-stale.yml
  .github/workflows/commit-message-check-format.yml
  .github/workflows/push-content.yml
  antora.yml
Labels: Review needed :book:

#1910 fix(bdm): mark code example as xml content
  modules/ROOT/pages/define-and-deploy-the-bdm.adoc
Labels: Review needed :book:

#1917 doc(RN): Update release note for release 2021.2-u3
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1924 doc(RN): Update release note for release 2021.1-0202
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1932 chore(2022.beta): update antora.yml
  antora.yml
Labels: Review needed :book:

#1927 Fix(timerEventTrigger): Add filter params for the GET method.
  modules/api/pages/bpm-api.adoc
Labels: Review done

#1904 doc(REST): troubleshooting section for the content-range header
  modules/ROOT/pages/rest-api-overview.adoc
Labels: Review done, Feedback integrated

#1938 feat(healthcheck): Add description of the healthcheck mechanism
  modules/runtime/pages/docker-deep-dive.adoc
  modules/runtime/pages/healthcheck-mechanism.adoc
  modules/runtime/runtime-nav.adoc
Labels: Review needed :book:

#1905 feat(runtime): add info about connector failure retry change
  modules/ROOT/pages/release-notes.adoc
Labels: Review done, Stale - no activity

#1941 chore(formatting): fix broken page formatting
  modules/ROOT/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1879 fix(troubleshooting sections): make them consistent
  modules/api/pages/bdm-in-rest-api.adoc
  modules/api/pages/rest-api-extensions.adoc
  modules/bonita-overview/pages/bonita-studio.adoc
  modules/bonita-overview/pages/ui-designer-overview.adoc
  modules/identity/pages/single-sign-on-with-kerberos.adoc
  modules/identity/pages/ssl.adoc
  modules/process/pages/generate-pdf-from-an-office-document.adoc
  modules/process/pages/insert-data-in-a-docx-odt-template.adoc
  modules/process/pages/ldap.adoc
  modules/runtime/pages/bonita-platform-setup.adoc
  modules/runtime/pages/cluster-administration.adoc
  modules/runtime/pages/performance-troubleshooting.adoc
Labels: Review needed :book:
