Repository bonitasoft/bonita-doc, pull requests merged in 2022-06, with the labels that each got.

#2062 feat(case process visu): caseInfo processInfo endpoints
  modules/ROOT/pages/release-notes.adoc
  modules/api/pages/actors-process-connectors-api.adoc
  modules/api/pages/cases-process-instance-api.adoc
Labels: Review needed :book:

#2064 chore: fix preview build errors
  .github/workflows/build-pr-preview.yml
Labels: Review done

#2063 feat (Process manager application): Update page modification steps to create a Process Manager Application
  modules/runtime/pages/process-manager-application.adoc
Labels: Review done

#2065 fix: remove comments in admin tools java example
  modules/ROOT/pages/create-administration-tools.adoc
Labels: Review needed :book:

#2068 chore(7.11): Put 7.11 out of support
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-pr-preview.yml
  .github/workflows/close-stale.yml
  .github/workflows/commit-message-check-format.yml
  .github/workflows/push-content.yml
  antora.yml
Labels: :warning: Do not merge :warning:

#2070 chore: use new `pr-diff-checker-action` version
  .github/workflows/contribution-check.yml
Labels: Review needed :book:

#2067 feat(STUDIO-4326): New startflow
  modules/ROOT/pages/build-a-process-for-deployment.adoc
  modules/api/pages/rest-api-extension-archetype.adoc
  modules/api/pages/rest-api-extensions.adoc
  modules/applications/pages/application-creation.adoc
  modules/applications/pages/use-bonita-acm.adoc
  modules/bonita-overview/pages/ui-designer-overview.adoc
  modules/bonita-overview/pages/using-Bonita-Studio.adoc
  modules/data/pages/define-and-deploy-the-bdm.adoc
  modules/getting-started/pages/create-application.adoc
  modules/getting-started/pages/define-business-data-model.adoc
  modules/getting-started/pages/define-who-can-do-what.adoc
  modules/getting-started/pages/draw-bpmn-diagram.adoc
  modules/identity/pages/bdm-access-control.adoc
  modules/identity/pages/organization-management-in-bonita-bpm-studio.adoc
  modules/pages-and-forms/pages/datetimes-management-tutorial.adoc
  modules/process/pages/diagram-tasks.adoc
  modules/process/pages/expressions-and-scripts.adoc
  modules/process/pages/optimize-user-tasklist.adoc
  modules/process/pages/process-testing-index.adoc
  modules/setup-dev-environment/pages/shared-project.adoc
  modules/setup-dev-environment/pages/workspaces-and-repositories.adoc
Labels: :construction: WIP :construction:

#2069 doc(RN): Prepare release note for 2022.2
  modules/ROOT/pages/release-notes.adoc
Labels: :construction: WIP :construction:

#2072 doc(deps): indicate that new Maven Repo is necessary
  modules/ROOT/pages/release-notes.adoc
Labels: :question: Question Asked :question:

#2075 chore: remove cloud branch reference
  .github/workflows/build-pr-preview.yml
Labels: :shipit: Ready to merge :shipit:
