Repository bonitasoft/bonita-doc, pull requests merged in 2022-08, with the labels that each got.

#2087 chore(humanTask): update /API/bpm/humanTask GET request filters details
  modules/api/pages/activities-tasks-flow-nodes-api.adoc
Labels: Review done

#2079 ci(jfrog): bonita jfrog access
  modules/setup-dev-environment/pages/configure-maven.adoc
  modules/software-extensibility/pages/bonita-repository-access.adoc
  modules/software-extensibility/software-extensibility-nav.adoc
Labels: Review needed :book:

#2104 feat: improve `case/process` visu information
  modules/ROOT/pages/release-notes.adoc
  modules/pages-and-forms/pages/customize-display-process-monitoring.adoc
Labels: :shipit: Ready to merge :shipit:

#2071 chore: simplify preview build
  .github/workflows/build-pr-preview.yml
Labels: Review needed :book:, no-stale

#2109 chore(2023.1): display search bar on site
  antora.yml
Labels: Review needed :book:

#2118 chore(preview-wf): simplify branch computation
  .github/workflows/build-pr-preview.yml
Labels: Review needed :book:

#2119 feat(OIDC): document new configuration options
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: 2022.1-u2 (7.14.2)
