Repository bonitasoft/bonita-doc, pull requests merged in 2022-03, with the labels that each got.

#1940 Update(update-studio): internet mandatory caution
  modules/version-update/pages/update-studio.adoc
Labels: Review needed :book:

#1952 doc(RN): Update release note for release 2021.2-u4
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1969 fix(release note): remove sec fixes ref
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1939 feat(bdm): Document of eager & lazy loading works
  modules/data/pages/define-and-deploy-the-bdm.adoc
Labels: Review needed :book:

#1946 fix(title): Fix title levels
  modules/api/pages/rest-api-authentication.adoc
Labels: Review needed :book:

#1984 doc(RN): Update release note for release 2021.1
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1985 feat(REST permissions): troubleshooting section
  modules/ROOT/pages/release-notes.adoc
  modules/identity/pages/rest-api-authorization.adoc
Labels: Review done

#1988 fix(docker): replace varversion w bonitaversion
  modules/ROOT/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1989 fix(formatting): fix docker-compose source sample
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1986 feat(dynamic permissions): improve release note
  modules/ROOT/pages/release-notes.adoc
Labels: Feedback integrated

#1973 feat(HTTP api): document Basic auth on Engine HTTP API
  modules/ROOT/pages/release-notes.adoc
  modules/api/pages/configure-client-of-bonita-bpm-engine.adoc
  modules/api/pages/create-your-first-project-with-the-engine-apis-and-maven.adoc
Labels: Review needed :book:

#1972 feat(docker): document new docker env variables
  modules/ROOT/pages/release-notes.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#1987 doc(SAML): Add SAML redirection URL lost issue troubleshooting section
  modules/ROOT/pages/single-sign-on-with-saml.adoc
Labels: Review done

#1994 fix(loggers configuration): addapt loggers conf to log4j2
  modules/data/pages/specify-data-in-a-process-definition.adoc
  modules/identity/pages/single-sign-on-with-kerberos.adoc
  modules/identity/pages/single-sign-on-with-oidc.adoc
  modules/identity/pages/single-sign-on-with-saml.adoc
  modules/runtime/pages/set-log-and-archive-levels.adoc
Labels: Review done

#1995 feat(OIDC): Authorization Code Flow supported with/without refressh token
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done

#1997 docs(web): Fix dead link for bpmn 2.0 (7.11)
  modules/ROOT/pages/draw-bpmn-diagram.adoc
Labels: Review done

#1933 doc(2022.2): initialize content
  .github/workflows/push-content.yml
  antora.yml
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#1998 docs(web): Fix errors in the Getting Started (2021.1)
  modules/ROOT/pages/define-business-data-model.adoc
  modules/ROOT/pages/define-who-can-do-what.adoc
Labels: :shipit: Ready to merge :shipit:

#2007 fix(cas): rephrase jaasAuthenticationService addition
  modules/ROOT/pages/single-sign-on-with-cas.adoc
Labels: :shipit: Ready to merge :shipit:

#2002 docs(BPM API): Split the big page into smaller ones
  modules/ROOT/pages/activities-tasks-flow-nodes-api.adoc
  modules/ROOT/pages/actors-process-connectors-api.adoc
  modules/ROOT/pages/bpm-api.adoc
  modules/ROOT/pages/cases-process-instance-api.adoc
  modules/ROOT/pages/data-documents-api.adoc
  modules/ROOT/taxonomy.adoc
Labels: Review done

#2011 fix(procdata): do not store BO in proc variable
  modules/ROOT/pages/specify-data-in-a-process-definition.adoc
Labels: Review needed :book:

#1944 update(getting started): add goals&download exple
  modules/getting-started/pages/getting-started-index.adoc
Labels: Review needed :book:, Stale - no activity

#2008 doc(rn): update purge-tool RN
  modules/ROOT/pages/purge-tool-changelog.adoc
Labels: Review needed :book:

#2010 doc(log4j): improve doc in docker volume mount explanations
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#2015 feat(docker): add more description for docker options
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review done

#2017 fix(OIDC): fix group path
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done

#2019 feat(OIDC): tomcat config with reverse proxy
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done
