Repository bonitasoft/bonita-doc, pull requests merged in 2022-01, with the labels that each got.

#1876 chore: add github workflow to check PR title and body
  .github/workflows/commit-message-check-format.yml
Labels: Review needed :book:

#1871 update(database) collation info MS SQL
  modules/ROOT/pages/database-configuration.adoc
Labels: Review needed :book:

#1875 feat(api): add info about filter deprecation on page api
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#1883 chore(pr): Adding pr diff check
  .github/workflows/commit-message-check-format.yml
Labels: newDocSite

#1877 feat(2021.2): activate pagination links in all pages
  antora.yml
Labels: Review done

#1838 update(resource management): line breaks
  modules/ROOT/pages/resource-management.adoc
Labels: Review needed :book:, Feedback integrated

#1866 feat(SAML): Destination is mandatory in IDP samlResponse
  modules/ROOT/pages/single-sign-on-with-saml.adoc
Labels: Review needed :book:

#1891 doc(RN): Update release note for release 2021.2-u2
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1817 fix: add more info on case-sensitiveness in search
  modules/api/pages/using-list-and-search-methods.adoc
  modules/runtime/pages/database-configuration.adoc
Labels: Review done, Stale - no activity

#1896 doc: Bonita 7.10 is out of support
  antora.yml
Labels: Review needed :book:

#1902 fix(RN): missing runtime bugfix in 2021.2-u2
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#1889 feat(dyn permissions): update VAR name to use to de-activate them
  modules/ROOT/pages/release-notes.adoc
  modules/identity/pages/ldap-synchronizer.adoc
  modules/identity/pages/rest-api-authorization.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:, :heavy_check_mark: Question Answered

#1898 feat(connectors): add doc how connector failure
  modules/process/pages/connector-archetype.adoc
  modules/runtime/pages/connectors-execution.adoc
Labels: Review needed :book:
