Repository bonitasoft/bonita-doc, pull requests merged in 2022-12, with the labels that each got.

#2254 docs(uid_variables): Call a Rest API on a condition
  modules/pages-and-forms/pages/variables.adoc
Labels: Review needed :book:

#2182 docs(SP): adjust the note to have subscription editions
  modules/ROOT/pages/active-directory-or-ldap-authentication.adoc
  modules/ROOT/pages/actors-process-connectors-api.adoc
  modules/ROOT/pages/admin-application-overview.adoc
  modules/ROOT/pages/admin-application-profiles-list.adoc
  modules/ROOT/pages/analytics.adoc
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/approaches-to-managing-organizations-and-actor-mapping.adoc
  modules/ROOT/pages/automating-builds.adoc
  modules/ROOT/pages/bonita-bpm-overview.adoc
  modules/ROOT/pages/bonita-layout.adoc
  modules/ROOT/pages/comparison-of-7-x-and-6-x.adoc
  modules/ROOT/pages/configure-maven.adoc
  modules/ROOT/pages/configuring-a-process.adoc
  modules/ROOT/pages/connectors-execution.adoc
  modules/ROOT/pages/create-a-report.adoc
  modules/ROOT/pages/creating-a-new-look-feel.adoc
  modules/ROOT/pages/customize-layouts.adoc
  modules/ROOT/pages/diagram-tasks.adoc
  modules/ROOT/pages/enforce-password-policy.adoc
  modules/ROOT/pages/engine-api-overview.adoc
  modules/ROOT/pages/engine-architecture-overview.adoc
  modules/ROOT/pages/event-handlers.adoc
  modules/ROOT/pages/execution-sequence-states-and-transactions.adoc
  modules/ROOT/pages/guest-user.adoc
  modules/ROOT/pages/key-concepts.adoc
  modules/ROOT/pages/ldap-synchronizer.adoc
  modules/ROOT/pages/licenses.adoc
  modules/ROOT/pages/living-application-layout.adoc
  modules/ROOT/pages/managing-look-feel.adoc
  modules/ROOT/pages/migrate-a-svn-repository-to-github.adoc
  modules/ROOT/pages/multi-language-pages.adoc
  modules/ROOT/pages/organization-overview.adoc
  modules/ROOT/pages/performance-troubleshooting.adoc
  modules/ROOT/pages/performance-tuning.adoc
  modules/ROOT/pages/pools-and-lanes.adoc
  modules/ROOT/pages/profile-list-portal.adoc
  modules/ROOT/pages/profiles-portal-overview.adoc
  modules/ROOT/pages/project-documentation-generation.adoc
  modules/ROOT/pages/purge-tool.adoc
  modules/ROOT/pages/queriable-logging.adoc
  modules/ROOT/pages/reporting-overview.adoc
  modules/ROOT/pages/run-a-process-from-bonita-bpm-studio-for-testing.adoc
  modules/ROOT/pages/runtime-installation-index.adoc
  modules/ROOT/pages/runtime-monitoring.adoc
  modules/ROOT/pages/set-up-a-reporting-database.adoc
  modules/ROOT/pages/set-up-continuous-integration.adoc
  modules/ROOT/pages/set-up-kpis.adoc
  modules/ROOT/pages/single-sign-on-with-cas.adoc
  modules/ROOT/pages/single-sign-on-with-kerberos.adoc
  modules/ROOT/pages/single-sign-on-with-saml.adoc
  modules/ROOT/pages/software-extensibility.adoc
  modules/ROOT/pages/use-bonita-acm.adoc
  modules/ROOT/pages/user-application-overview.adoc
  modules/ROOT/pages/what-is-bonita.adoc
Labels: Review done

#2208 docs(Tomcat bundle): change the troubleshooting section format
  .github/styles/Vocab/Base/accept.txt
  modules/runtime/pages/tomcat-bundle.adoc
Labels: Review needed :book:, Feedback integrated

#2246 docs(2022.1): Update release note for 7.14.5
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: :shipit: Ready to merge :shipit:, Review needed :book:

#2273 ci: use bonitasoft/actions pr-title-conventional-commits
  .github/workflows/commit-checks.yml
  .github/workflows/contribution-checks.yml
Labels: Review needed :book:

#2274 fix(docker): add missing part on log4j2 volume mount
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#2275 fix(typo): fix typo on main page tile
  modules/ROOT/pages/index.adoc
Labels: Review needed :book:

#2225 docs(Bonita repository access): Use new format for troubleshooting sections
  modules/software-extensibility/pages/bonita-repository-access.adoc
Labels: Review needed :book:
