Repository bonitasoft/bonita-doc, pull requests merged in 2023-11, with the labels that each got.

#2455 docs(sca): documentation related to the new SCA mode
  antora.yml
  modules/bonita-overview/pages/managing-extension-studio.adoc
  modules/bonita-overview/pages/project-structure.adoc
  modules/build-run/assets/images/build_phase.png
  modules/build-run/build-run-nav.adoc
  modules/build-run/pages/application-overview.adoc
  modules/build-run/pages/application-user-flow.adoc
  modules/build-run/pages/build-application.adoc
  modules/build-run/pages/run-application.adoc
  modules/getting-started/getting-started-nav.adoc
  modules/getting-started/pages/getting-started-index.adoc
  modules/getting-started/pages/package-and-deploy-sca-application.adoc
  modules/identity/pages/active-directory-or-ldap-authentication.adoc
  modules/identity/pages/enforce-password-policy.adoc
  modules/identity/pages/single-sign-on-with-cas.adoc
  modules/identity/pages/single-sign-on-with-kerberos.adoc
  modules/runtime/pages/admin-application-overview.adoc
  modules/runtime/pages/bonita-applications-deep-dive.adoc
  modules/runtime/pages/bonita-applications-interface-overview.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
  modules/runtime/pages/bonita-platform-setup.adoc
  modules/runtime/pages/custom-deployment.adoc
  modules/runtime/pages/reporting-app.adoc
  modules/runtime/pages/super-administrator-application-overview.adoc
  modules/runtime/pages/tomcat-bundle.adoc
  modules/runtime/pages/user-application-overview.adoc
  modules/software-extensibility/pages/bonita-repository-access.adoc
Labels: SCA 👷🏻‍♂️

#2497 docs(session): add cookie constraint note
  modules/identity/pages/user-authentication-overview.adoc
Labels: Review needed :book:

#2506 feat(release): mark 2023.2 as GA
  antora.yml
Labels: Review done

#2507 feat(Software): Update RHEL & CentOS support
  modules/runtime/pages/hardware-and-software-requirements.adoc
Labels: Review needed :book:

#2517 feat(ReleaseNote): Add 8.0.1 release note (2023.1-u1)
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2531 docs: update product-versioning.adoc on 2023.1
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2534 feat(ReleaseNote): Create Release Note for 2022.1-u7/7.14.7
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2533 feat(ReleaseNote): Create Release note for 2022.2-u6/7.15.6
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2532 docs: Update product-versioning.adoc on 2022.1
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2530 docs: Update Product version compatibility on 2022.2
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2542 docs(release note): add bugfixes for 2023.1-u2
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2543 docs(release note): add bugfixes for 2023.2-u1
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:
