Repository bonitasoft/bonita-doc, pull requests merged in 2023-03, with the labels that each got.

#2329 docs(OIDC): add missing logout documentation
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review needed :book:

#2319 docs(OIDC): support auth methods to get token by their spec name
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review needed :book:, :fire:Merge only on release :skull_and_crossbones:

#2336 chore(2023.2): initialize content
  .github/workflows/push-content.yml
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2330 docs(angular.js): mention updates to Angular.js
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/angular-js-UID-fork.adoc
  modules/version-update/version-update-nav.adoc
Labels: :construction: WIP :construction:

#2338 docs(update): add app packager ref in release-notes
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2341 feat(docker): BAR as a docker registry
  antora.yml
  modules/runtime/pages/bonita-docker-installation.adoc
  modules/software-extensibility/pages/bonita-repository-access.adoc
  modules/software-extensibility/software-extensibility-nav.adoc
Labels: :construction: WIP :construction:
