Repository bonitasoft/bonita-doc, pull requests merged in 2023-05, with the labels that each got.

#2381 feat(sca): document new INSTALL_PROVIDED_PAGES docker param
  modules/runtime/pages/bonita-docker-installation.adoc
Labels: Review needed :book:

#2388 docs(release note): add release note for 7.13.8
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2380 docs(GA): Update GA details
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/update-tools-changelog.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:

#2389 chore(vale): Cleanup Vale syntax checker (not used)
  .github/styles/Vocab/Base/accept.txt
  .github/styles/Vocab/Base/reject.txt
  .github/workflows/contribution-checks.yml
  .vale.ini
Labels: Review done

#2390 docs(OIDC): add logout notes
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review needed :book:

#2397 docs(RN): 2022.1-u6
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2407 docs(RN): warning regarding experimental packaging tool
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:
