Repository bonitasoft/bonita-doc, pull requests merged in 2023-10, with the labels that each got.

#2454 feat(doc): update maintenance doc
  modules/ROOT/pages/about.adoc
  modules/bonita-overview/pages/bonita-bpm-overview.adoc
  modules/data/pages/define-and-deploy-the-bdm.adoc
  modules/identity/pages/all-api-permissions.adoc
  modules/identity/pages/special-users.adoc
  modules/runtime/pages/admin-application-process-list.adoc
  modules/runtime/pages/application-directory.adoc
  modules/runtime/pages/bdm-management-in-bonita-applications.adoc
  modules/runtime/pages/bonita-applications-interface-overview.adoc
  modules/runtime/pages/how-a-bdm-is-deployed.adoc
  modules/runtime/pages/pause-and-resume-bpm-services.adoc
  modules/runtime/pages/platform-maintenance-mode.adoc
  modules/runtime/pages/super-administrator-application-index.adoc
  modules/runtime/pages/super-administrator-application-overview.adoc
  modules/runtime/runtime-nav.adoc
  modules/version-update/pages/update-with-migration-tool.adoc
  modules/version-update/pages/update-with-update-tool.adoc
  modules/version-update/pages/upgrade-from-community-to-a-subscription-edition.adoc
Labels: Review done, Feedback integrated

#2456 feat(doc): Display the public Vulnerability Reporting Policy
  antora.yml
  modules/ROOT/build-community-nav.adoc
  modules/contributing/contributing-nav.adoc
  modules/contributing/pages/building-community-edition-from-source.adoc
  modules/contributing/pages/vulnerability-reporting-policy.adoc
Labels: Review needed :book:

#2463 chore(2023.2): initialize content
  .github/workflows/push-content.yml
  antora.yml
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2458 docs(release note): Add maintenance mode to 2023.2 RN
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2474 fix(release-notes): use attribute instead of hard coded version
  modules/ROOT/pages/release-notes.adoc
Labels: Review needed :book:

#2475 chore: mark 2021.2 as “out-of-support”
  .github/workflows/build-pr-preview.yml
  .github/workflows/close-stale.yml
  .github/workflows/commit-checks.yml
  .github/workflows/compress-images.yml
  .github/workflows/contribution-checks.yml
  .github/workflows/publish-pr-preview.yml
  .github/workflows/push-content.yml
  antora.yml
Labels: Review needed :book:

#2467 docs(sca): Adding user flows.
  antora.yml
  modules/build-run/build-run-nav.adoc
  modules/build-run/pages/sca-user-flows.adoc
Labels: :construction: WIP :construction:, SCA 👷🏻‍♂️

#2479 feat(sca): update runtime page to take into account sca
  modules/runtime/pages/admin-application-overview.adoc
  modules/runtime/pages/bonita-applications-interface-overview.adoc
  modules/runtime/pages/custom-deployment.adoc
  modules/runtime/pages/super-administrator-application-overview.adoc
Labels: SCA 👷🏻‍♂️

#2481 feat(extension): application classpath
  modules/bonita-overview/pages/managing-extension-studio.adoc
  modules/bonita-overview/pages/project-structure.adoc
Labels: SCA 👷🏻‍♂️
