Repository bonitasoft/bonita-doc, pull requests merged in 2023-08, with the labels that each got.

#2440 docs(release note): add release note for 2022.2-u5
  modules/ROOT/pages/release-notes.adoc
Labels: Review done, :shipit: Ready to merge :shipit:, Feedback integrated

#2432 feat(releaseNote): add removal for custom connectors and provided script
  modules/ROOT/pages/release-notes.adoc
Labels: :shipit: Ready to merge :shipit:, Stale - no activity

#2415 fix(2023.2): correctly generate links to the javadoc v9.0
  antora.yml
Labels: Review needed :book:, no-stale
