Repository bonitasoft/bonita-doc, pull requests merged in 2023-02, with the labels that each got.

#2297 fix(Manual operations): simplify documentation
  modules/version-update/pages/update-with-migration-tool.adoc
  modules/version-update/pages/update-with-update-tool.adoc
Labels: Stale - no activity

#2314 docs: Accessibility in UI-designer
  modules/ROOT/pages/release-notes.adoc
  modules/pages-and-forms/pages/widgets.adoc
Labels: Review needed :book:

#2320 docs(OIDC): Redirect URI is adding port zero to the URL
  modules/identity/pages/single-sign-on-with-oidc.adoc
Labels: Review done, Feedback integrated

#2322 docs(SSO): User account provisionning via IDP
  modules/identity/pages/single-sign-on-with-oidc.adoc
  modules/identity/pages/single-sign-on-with-saml.adoc
  modules/identity/pages/user-account-provisioning-with-sso.adoc
Labels: Review done

#2324 fix(asciidoc): workaround wrong Maven pom xml display
  modules/ROOT/pages/custom-authorization-rule-mapping.adoc
  modules/ROOT/pages/event-handlers.adoc
Labels: :shipit: Ready to merge :shipit:

#2326 docs(SSO): User account provisioning via IDP
  modules/identity/identity-nav.adoc
  modules/identity/pages/user-account-provisioning-with-sso.adoc
Labels: Review done

#2325 docs(release): adjustments and new values added
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#2327 docs(release): add user account provisioning to RN
  modules/ROOT/pages/release-notes.adoc
Labels: Review done
