Repository bonitasoft/bonita-doc, pull requests merged in 2024-09, with the labels that each got.

#2820 docs(uib): add node redundancy info
  modules/applications/pages/ui-builder/faq.adoc
  modules/applications/pages/ui-builder/production-packaging.adoc
Labels: Review needed :book:

#2823 docs(uib): retrieve user avatar icon
  modules/applications/applications-nav.adoc
  modules/applications/assets/images/ui-builder/guides/firstname.png
  modules/applications/assets/images/ui-builder/guides/query-get-users.png
  modules/applications/assets/images/ui-builder/guides/user-avatar.png
  modules/applications/assets/images/ui-builder/guides/user-list-widget.png
  modules/applications/assets/images/ui-builder/guides/user-list.png
  modules/applications/pages/ui-builder/bonita-ui-builder-best-practices.adoc
  modules/applications/pages/ui-builder/how-to-retrieve-user-avatar.adoc
Labels: Review needed :book:

#2824 docs(uib): configure healthcheck in production
  modules/applications/pages/ui-builder/production-packaging.adoc
  modules/applications/pages/ui-builder/ui-builder-docker-installation.adoc
Labels: Review needed :book:

#2815 docs(uib): add document viewer issue in FAQ
  modules/applications/pages/ui-builder/faq.adoc
Labels: Review done

#2831 docs(uib): hr management use cases
  modules/applications/applications-nav.adoc
  modules/applications/pages/ui-builder/bonita-ui-builder-best-practices.adoc
  modules/applications/pages/ui-builder/common-apis-to-use.adoc
Labels: Review needed :book:

#2804 docs: very small update to gdpr-guidelines.adoc
  modules/best-practices/pages/gdpr-guidelines.adoc
Labels: Stale - no activity
