Repository bonitasoft/bonita-doc, pull requests merged in 2024-04, with the labels that each got.

#2640 fix(link): Update link to license page to new CSC
  modules/runtime/pages/licenses.adoc
Labels: Stale - no activity

#2662 docs(widget): rich text area and xss
  modules/pages-and-forms/pages/widgets.adoc
Labels: Review needed :book:

#2675 docs(releaseNote): Update release-notes.adoc for 9.0.4
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/product-versioning.adoc
Labels: Review needed :book:

#2663 fix(sanitizer): document how to set sanitizer log level
  modules/security/pages/sanitizer-security.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:

#2679 docs(sanitizer filter): follow changes on default value
  modules/security/pages/sanitizer-security.adoc
Labels: Review done, Feedback integrated

#2680 docs(building-community): improve building community from source section
  modules/contributing/pages/building-bonita-admin-application.adoc
  modules/contributing/pages/building-bonita-application-directory.adoc
  modules/contributing/pages/building-bonita-data-repository.adoc
  modules/contributing/pages/building-bonita-distrib.adoc
  modules/contributing/pages/building-bonita-engine.adoc
  modules/contributing/pages/building-bonita-portal-js.adoc
  modules/contributing/pages/building-bonita-studio.adoc
  modules/contributing/pages/building-bonita-super-admin-application.adoc
  modules/contributing/pages/building-bonita-ui-designer.adoc
  modules/contributing/pages/building-bonita-user-application.adoc
  modules/contributing/pages/building-bonita-web-pages.adoc
  modules/contributing/pages/building-community-edition-from-source.adoc
Labels: Review needed :book:, :warning: Do not merge :warning:
