Repository bonitasoft/bonita-doc, pull requests merged in 2024-10, with the labels that each got.

#2882 feat(release): mark 2024.3 as GA
  antora.yml
Labels: :fire:Merge only on release :skull_and_crossbones:

#2807 docs(purgeTool): changelog and other
  modules/runtime/pages/purge-tool-changelog.adoc
  modules/runtime/pages/purge-tool.adoc
Labels: no-stale

#2898 fix: update link to maven central
  modules/api/pages/rest-api-extensions.adoc
Labels: Review needed :book:

#2897 chore(uib): update production docker-compose.yml
  modules/applications/examples/ui-builder/production/docker-compose.yml
Labels: :shipit: Ready to merge :shipit:

#2899 fix: use correct CSC URL
  modules/version-update/pages/update-studio.adoc
Labels: Review needed :book:
