Repository bonitasoft/bonita-doc, pull requests merged in 2025-02, with the labels that each got.

#2964 feat(MTR): notify external-identity-mapping removal
  modules/ROOT/pages/release-notes.adoc
  modules/integration/pages/event-handlers.adoc
Labels: Feedback integrated

#2963 feat(MTR): remove tenantid from JAAS / LDAP config
  modules/ROOT/pages/release-notes.adoc
  modules/identity/pages/active-directory-or-ldap-authentication.adoc
  modules/identity/pages/single-sign-on-with-cas.adoc
Labels: Feedback integrated

#2968 docs(update-tool): notify tool script renaming
  modules/ROOT/pages/release-notes.adoc
  modules/version-update/pages/update-tools-changelog.adoc
  modules/version-update/pages/update-with-update-tool.adoc
Labels: Review needed :book:

#2973 refactor(MTR): remove references to tenant for LDAP Synchronizer
  modules/ROOT/pages/release-notes.adoc
  modules/identity/pages/ldap-synchronizer.adoc
Labels: Review needed :book:

#2961 feat: Document several deployment strategies for UIB pages
  modules/applications/pages/ui-builder/package-and-deploy-your-application.adoc
  modules/best-practices/pages/design-methodology.adoc
  modules/getting-started/pages/package-and-deploy-sca-application.adoc
Labels: Stale - no activity

#2977 docs(RN): document PlatformAPI deprecation removals
  modules/ROOT/pages/release-notes.adoc
Labels: Review done

#2970 docs(setup-tool): handle tenantid removal from configuration files
  modules/ROOT/pages/api-extensions.adoc
  modules/ROOT/pages/release-notes.adoc
  modules/api/pages/manage-the-platform.adoc
  modules/api/pages/queriable-logging.adoc
  modules/api/pages/rest-api-extension-archetype.adoc
  modules/applications/pages/ui-designer/use-bonita-acm.adoc
  modules/data/pages/define-and-deploy-the-bdm.adoc
  modules/identity/pages/bdm-access-control.adoc
  modules/identity/pages/custom-authorization-rule-mapping.adoc
  modules/identity/pages/enforce-password-policy.adoc
  modules/identity/pages/guest-user.adoc
  modules/identity/pages/rest-api-authorization.adoc
  modules/identity/pages/single-sign-on-with-cas.adoc
  modules/identity/pages/single-sign-on-with-kerberos.adoc
  modules/identity/pages/single-sign-on-with-oidc.adoc
  modules/identity/pages/single-sign-on-with-saml.adoc
  modules/identity/pages/tenant-admin-credentials.adoc
  modules/identity/pages/user-account-provisioning-with-sso.adoc
  modules/identity/pages/user-authentication-overview.adoc
  modules/integration/pages/event-handlers.adoc
  modules/pages-and-forms/pages/pages-development.adoc
  modules/runtime/pages/administration-index.adoc
  modules/runtime/pages/bonita-docker-installation.adoc
  modules/runtime/pages/cluster-administration.adoc
  modules/runtime/pages/engine-architecture-overview.adoc
  modules/runtime/pages/first-steps-after-setup.adoc
  modules/runtime/pages/overview-of-bonita-bpm-in-a-cluster.adoc
  modules/runtime/pages/tomcat-bundle.adoc
  modules/version-update/pages/update-with-migration-tool.adoc
  modules/version-update/pages/update-with-update-tool.adoc
Labels: Review done

#2980 docs: Bump UIB version
  antora.yml
  modules/applications/examples/ui-builder/development/docker-compose.yml
  modules/applications/pages/ui-builder/bonita-ui-builder.adoc
Labels: :fire:Merge only on release :skull_and_crossbones:
